const L = (de, en, fa) => ({ de, en, fa })
export const copy = {
  title: L('Fleischner-Kriterien', 'Fleischner criteria', 'معیارهای Fleischner'),
  subtitle: L('Lungenrundherde einordnen. Kontrollen gezielt planen.', 'Classify pulmonary nodules. Plan appropriate follow-up.', 'ندول‌های ریوی را طبقه‌بندی کنید و پیگیری مناسب را انتخاب کنید.'),
  back: L('Thorax', 'Thorax', 'توراکس'),
  toc: L('In dieser Lektion', 'In this lesson', 'در این درس'),
  badge: L('CT · Fleischner Society 2017', 'CT · Fleischner Society 2017', 'CT · انجمن Fleischner ۲۰۱۷'),
  intro: L('Vom Zufallsbefund zur begründeten Empfehlung: erst Anwendbarkeit prüfen, dann Dichte, Anzahl, Größe und Risiko zusammenführen.', 'From an incidental finding to a reasoned recommendation: check eligibility, then combine attenuation, number, size and risk.', 'از یافته اتفاقی تا توصیه مستدل: ابتدا قابلیت کاربرد و سپس دانسیته، تعداد، اندازه و خطر را بررسی کنید.'),
  read: L('Als gelesen markieren', 'Mark as read', 'علامت‌گذاری به‌عنوان خوانده‌شده'),
  done: L('Als gelesen markiert', 'Marked as read', 'خوانده‌شده'),
  auth: L('Bitte anmelden, um den Lernfortschritt zu speichern.', 'Please sign in to save your progress.', 'برای ذخیره پیشرفت وارد شوید.'),
  login: L('Anmelden', 'Sign in', 'ورود'),
  note: L('Merke', 'Key point', 'نکته'),
  solution: L('Lösung anzeigen', 'Show answer', 'نمایش پاسخ'),
  hide: L('Lösung ausblenden', 'Hide answer', 'پنهان کردن پاسخ'),
  casesIntro: L('Fiktive Lernfälle. Entscheide zuerst selbst, bevor du die Begründung öffnest. Sofern nicht anders angegeben: inzidenteller CT-Befund, keine bekannte Tumorerkrankung, keine Immunsuppression.', 'Fictional learning cases. Decide before revealing the explanation. Unless stated otherwise: incidental CT finding, no known cancer and no immunosuppression.', 'موارد آموزشی فرضی: پیش از نمایش پاسخ تصمیم بگیرید. مگر آنکه خلاف آن ذکر شود: یافته اتفاقی CT، بدون سرطان شناخته‌شده و بدون سرکوب ایمنی.'),
  sourceNote: L('Eigenständig formulierte Lernzusammenfassung der Empfehlungen von 2017. Die Intervalle sind Entscheidungsspielräume; Morphologie, Verlauf, Begleiterkrankungen und Patientenpräferenzen gehören zur Empfehlung.', 'An independently written learning summary of the 2017 recommendations. Intervals allow clinical discretion; morphology, evolution, comorbidity and patient preferences inform the recommendation.', 'خلاصه آموزشی با نگارش مستقل بر پایه توصیه‌های ۲۰۱۷. بازه‌های زمانی امکان تصمیم‌گیری بالینی می‌دهند؛ مورفولوژی، سیر، بیماری‌های همراه و ترجیح بیمار نیز مهم‌اند.'),
}

const no = L('Keine routinemäßige Kontrolle', 'No routine follow-up', 'بدون پیگیری روتین')
const optional12 = L('CT nach 12 Monaten optional', 'Optional CT at 12 months', 'CT اختیاری در ۱۲ ماه')
const singleLow = L('CT: 6–12 Monate; 18–24 Monate erwägen', 'CT: 6–12 months; consider 18–24 months', 'CT: در ۶–۱۲ ماه؛ بررسی مجدد در ۱۸–۲۴ ماه قابل‌بررسی است')
const singleHigh = L('CT: 6–12 und 18–24 Monate', 'CT: 6–12 and 18–24 months', 'CT: در ۶–۱۲ و ۱۸–۲۴ ماه')
const multipleLow = L('CT: 3–6 Monate; 18–24 Monate erwägen', 'CT: 3–6 months; consider 18–24 months', 'CT: در ۳–۶ ماه؛ بررسی مجدد در ۱۸–۲۴ ماه قابل‌بررسی است')
const multipleHigh = L('CT: 3–6 und 18–24 Monate', 'CT: 3–6 and 18–24 months', 'CT: در ۳–۶ و ۱۸–۲۴ ماه')
const large = L('CT nach etwa 3 Monaten, PET/CT oder Gewebegewinnung erwägen', 'Consider CT at about 3 months, PET/CT or tissue sampling', 'CT حدود ۳ ماه، PET/CT یا نمونه‌برداری را بررسی کنید')
const single = L('Einzeln', 'Single', 'منفرد')
const multiple = L('Multipel', 'Multiple', 'متعدد')

export const sections = [
  { id: 'geltung', title: L('01 · Wann gilt Fleischner?', '01 · When does Fleischner apply?', '۰۱ · چه زمانی کاربرد دارد؟'),
    cards: [
      [L('Zufallsbefund ab 35 Jahren', 'Incidental finding, age ≥35', 'یافته اتفاقی در سن ≥۳۵ سال'), L('Für inzidentell im CT entdeckte, unklare Lungenrundherde bei Erwachsenen ab 35 Jahren.', 'For indeterminate pulmonary nodules incidentally detected on CT in adults aged 35 or older.', 'برای ندول‌های ریوی نامعین که به‌طور اتفاقی در CT بزرگسالان ۳۵ ساله یا بالاتر یافت می‌شوند.')],
      [L('Hier nicht anwenden', 'Outside its scope', 'خارج از دامنه کاربرد'), L('Nicht für Lungenkrebs-Screening, bekannte primäre Tumorerkrankung oder Immunsuppression. Unter 35 Jahren individuell vorgehen. Im Screening gilt das jeweilige Screening-Protokoll, beispielsweise Lung-RADS.', 'Not for lung cancer screening, known primary cancer or immunosuppression. Below age 35, individualize management. In screening, use the applicable screening protocol, such as Lung-RADS.', 'برای غربالگری سرطان ریه، سرطان اولیه شناخته‌شده یا سرکوب ایمنی نیست. زیر ۳۵ سال تصمیم فردی لازم است. در غربالگری از پروتکل مربوط، مانند Lung-RADS، استفاده کنید.')],
      [L('Vor der Tabelle', 'Before the table', 'پیش از جدول'), L('Voraufnahmen suchen und eindeutig benigne Befunde erkennen. Typische intrapulmonale Lymphknoten, benigne Verkalkungsmuster oder makroskopisches Fett können eine Verlaufskontrolle entbehrlich machen. Fissurennähe allein beweist keine Benignität.', 'Review prior imaging and identify unequivocally benign findings. Typical intrapulmonary lymph nodes, benign calcification patterns or macroscopic fat may obviate follow-up. Fissural proximity alone does not establish benignity.', 'تصاویر قبلی و نشانه‌های قطعاً خوش‌خیم را بررسی کنید. گره لنفاوی داخل‌ریوی تیپیک، کلسیفیکاسیون خوش‌خیم یا چربی ماکروسکوپی ممکن است نیاز به پیگیری را رفع کند. مجاورت فیشور به‌تنهایی کافی نیست.')],
    ] },
  { id: 'einordnen', title: L('02 · Dichte & Risiko', '02 · Attenuation & risk', '۰۲ · دانسیته و خطر'),
    cards: [
      [L('Solide', 'Solid', 'جامد'), L('Die Verdichtung verdeckt die zugrunde liegenden Gefäße vollständig.', 'The opacity completely obscures underlying vessels.', 'کدورت، عروق زمینه‌ای را کاملاً می‌پوشاند.')],
      [L('Reines Milchglas', 'Pure ground glass', 'شیشه‌مات خالص'), L('Gefäße bleiben erkennbar; keine solide Komponente. Gehört zu den subsoliden Herden.', 'Vessels remain visible; no solid component. A subsolid nodule type.', 'عروق قابل‌مشاهده‌اند و جزء جامد وجود ندارد. از انواع ندول نیمه‌جامد است.')],
      [L('Teilsolide', 'Part solid', 'بخشی جامد'), L('Milchglas und solide Komponente nebeneinander. Gesamtherd und soliden Anteil getrennt messen.', 'Ground glass plus a solid component. Measure the whole nodule and the solid component separately.', 'شیشه‌مات همراه با جزء جامد. کل ندول و جزء جامد را جداگانه اندازه بگیرید.')],
    ],
    note: L('Risiko ist mehr als Rauchen: Alter, starke Tabakexposition, Familienanamnese, Emphysem/Fibrose sowie Oberlappenlage, Spikulation und Größe gemeinsam beurteilen. Die subsolide Tabelle hat keine getrennten Spalten für niedriges und hohes Risiko.', 'Risk is more than smoking: consider age, heavy tobacco exposure, family history, emphysema/fibrosis, upper-lobe location, spiculation and size together. The subsolid table does not split into low- and high-risk columns.', 'خطر فقط سیگار نیست: سن، مصرف زیاد دخانیات، سابقه خانوادگی، آمفیزم/فیبروز، محل لوب فوقانی، اسپیکولاسیون و اندازه را با هم بررسی کنید. جدول نیمه‌جامد ستون جداگانه کم‌خطر و پرخطر ندارد.') },
  { id: 'messen', title: L('03 · Richtig messen', '03 · Measure correctly', '۰۳ · اندازه‌گیری صحیح'),
    cards: [
      [L('Dünnschicht-CT', 'Thin-section CT', 'CT با برش نازک'), L('Zusammenhängende Schichten ≤1,5 mm, typischerweise 1 mm. Im Lungenfenster und multiplanar beurteilen. Verlauf möglichst mit vergleichbarer Technik und niedriger Dosis.', 'Use contiguous sections ≤1.5 mm, typically 1 mm. Assess in lung windows and multiple planes. Use comparable technique and low dose for surveillance.', 'برش‌های پیوسته ≤۱٫۵ میلی‌متر، معمولاً ۱ میلی‌متر. پنجره ریه و نماهای چندصفحه‌ای را بررسی کنید. برای پیگیری از تکنیک مشابه و دوز پایین استفاده کنید.')],
      [L('Mittlerer Durchmesser', 'Mean diameter', 'قطر میانگین'), L('Bei kleinen Herden lange und dazu senkrechte kurze Achse in derselben Ebene messen: (lang + kurz) / 2, auf ganze Millimeter runden. Beispiel: 8 × 6 mm → 7 mm. Die Ebene mit der größten Ausdehnung wählen.', 'For small nodules, measure long and perpendicular short axes in the same plane: (long + short) / 2, rounded to whole millimeters. Example: 8 × 6 mm → 7 mm. Choose the plane showing the greatest dimensions.', 'در ندول کوچک، محور بلند و محور کوتاه عمود بر آن را در یک صفحه اندازه بگیرید: مجموع دو محور تقسیم بر ۲، گرد به میلی‌متر کامل. مثال: ۸ × ۶ ← ۷ میلی‌متر. صفحه با بیشترین ابعاد را انتخاب کنید.')],
      [L('Wachstum erkennen', 'Recognize growth', 'تشخیص رشد'), L('Eine Durchmesserzunahme ≥2 mm spricht für relevantes Wachstum. Messvariabilität beachten. Bei subsoliden Herden zusätzlich nach neuem oder wachsendem solidem Anteil suchen; auch bei stabiler Gesamtgröße relevant.', 'A diameter increase ≥2 mm indicates meaningful growth. Account for measurement variability. In subsolid nodules, also look for a new or enlarging solid component, even if overall size is stable.', 'افزایش قطر ≥۲ میلی‌متر نشان‌دهنده رشد قابل‌توجه است؛ تغییرپذیری اندازه‌گیری را لحاظ کنید. در ندول نیمه‌جامد، جزء جامد جدید یا در حال رشد حتی با اندازه کلی ثابت مهم است.')],
    ] },
  { id: 'solide', title: L('04 · Solide Rundherde', '04 · Solid nodules', '۰۴ · ندول‌های جامد'),
    lead: L('Intervalle ab Ausgangs-CT. „Optional“ bedeutet eine begründete Einzelfallentscheidung.', 'Intervals are measured from baseline CT. “Optional” calls for an individualized decision.', 'بازه‌ها از CT پایه محاسبه می‌شوند. «اختیاری» به معنی تصمیم‌گیری فردی مستدل است.'),
    headers: [L('Anzahl', 'Number', 'تعداد'), L('Größe', 'Size', 'اندازه'), L('Niedriges Risiko', 'Low risk', 'خطر پایین'), L('Hohes Risiko', 'High risk', 'خطر بالا')],
    rows: [[single, '<6 mm', no, optional12], [single, '6–8 mm', singleLow, singleHigh], [single, '>8 mm', large, large], [multiple, '<6 mm', no, optional12], [multiple, '6–8 mm', multipleLow, multipleHigh], [multiple, '>8 mm', multipleLow, multipleHigh]],
    note: L('Bei multiplen Herden führt der suspekteste Herd, nicht automatisch der größte. Ein dominanter suspekter Herd kann eine Abklärung nach dem Einzelherd-Schema erfordern. Genau 8 mm liegt in „6–8 mm“, nicht in „>8 mm“.', 'With multiple nodules, the most suspicious nodule guides management, not necessarily the largest. A dominant suspicious nodule may require work-up according to the single-nodule pathway. Exactly 8 mm belongs to “6–8 mm”, not “>8 mm”.', 'در ندول‌های متعدد، مشکوک‌ترین ندول تعیین‌کننده است، نه لزوماً بزرگ‌ترین. ندول غالب مشکوک ممکن است بررسی طبق مسیر ندول منفرد نیاز داشته باشد. دقیقاً ۸ میلی‌متر در گروه ۶–۸ است، نه >۸.') },
  { id: 'subsolide', title: L('05 · Subsolide Rundherde', '05 · Subsolid nodules', '۰۵ · ندول‌های نیمه‌جامد'),
    headers: [L('Muster', 'Pattern', 'الگو'), '<6 mm', '≥6 mm'],
    rows: [
      [L('Einzeln · reines Milchglas', 'Single · pure ground glass', 'منفرد · شیشه‌مات خالص'), no, L('CT nach 6–12 Monaten; bei Persistenz alle 2 Jahre bis 5 Jahre', 'CT at 6–12 months; if persistent, every 2 years until 5 years', 'CT در ۶–۱۲ ماه؛ در صورت ماندگاری هر ۲ سال تا ۵ سال')],
      [L('Einzeln · teilsolide', 'Single · part solid', 'منفرد · بخشی جامد'), no, L('CT nach 3–6 Monaten; bei Persistenz und solidem Anteil <6 mm jährlich für 5 Jahre', 'CT at 3–6 months; if persistent and solid component <6 mm, annually for 5 years', 'CT در ۳–۶ ماه؛ اگر پایدار بماند و جزء جامد <۶ میلی‌متر باشد، سالانه به مدت ۵ سال')],
      [L('Multipel · subsolide', 'Multiple · subsolid', 'متعدد · نیمه‌جامد'), L('CT nach 3–6 Monaten; bei Stabilität CT nach 2 und 4 Jahren erwägen', 'CT at 3–6 months; if stable, consider CT at 2 and 4 years', 'CT در ۳–۶ ماه؛ اگر ثابت باشد CT در ۲ و ۴ سال قابل‌بررسی است'), L('CT nach 3–6 Monaten; weiteres Vorgehen nach dem suspektesten Herd', 'CT at 3–6 months; subsequent management guided by the most suspicious nodule', 'CT در ۳–۶ ماه؛ ادامه بر اساس مشکوک‌ترین ندول')],
    ],
    note: L('Die Größenspalten beziehen sich auf den Gesamtherd; bei multiplen Herden genügt ein Herd ≥6 mm. Einzelne subsolide Herde <6 mm mit suspekter Morphologie oder erhöhtem Risiko können Kontrollen nach 2 und 4 Jahren rechtfertigen.', 'Size columns refer to the whole nodule; for multiple nodules, at least one ≥6 mm selects that column. Selected single subsolid nodules <6 mm with suspicious morphology or increased risk may warrant follow-up at 2 and 4 years.', 'ستون اندازه مربوط به کل ندول است؛ در موارد متعدد وجود یک ندول ≥۶ میلی‌متر کافی است. در برخی ندول‌های نیمه‌جامد منفرد <۶ با مورفولوژی مشکوک یا خطر بالا، پیگیری در ۲ و ۴ سال قابل‌بررسی است.'),
    warning: L('Solider Anteil ≥6 mm: bei Persistenz hochgradig suspekt. Kurzfristige CT nach 3–6 Monaten zur Persistenzprüfung erwägen und weitere Abklärung individuell festlegen. Bei Wachstum, besonders suspekter Morphologie oder solidem Anteil >8 mm kommen PET/CT, Biopsie oder Resektion infrage. Nicht automatisch in die jährliche Routinekontrolle einordnen.', 'Solid component ≥6 mm: highly suspicious if persistent. Consider CT at 3–6 months to establish persistence and individualize further work-up. Growth, particularly suspicious morphology or a solid component >8 mm warrant consideration of PET/CT, biopsy or resection. Do not automatically assign annual routine surveillance.', 'جزء جامد ≥۶ میلی‌متر در صورت ماندگاری بسیار مشکوک است. CT در ۳–۶ ماه برای تأیید ماندگاری و بررسی تکمیلی فردی را در نظر بگیرید. در رشد، مورفولوژی بسیار مشکوک یا جزء جامد >۸ میلی‌متر، PET/CT، بیوپسی یا رزکسیون مطرح است. آن را خودکار به پیگیری روتین سالانه ارجاع ندهید.') },
  { id: 'befund', title: L('06 · Vom Befund zur Empfehlung', '06 · From finding to recommendation', '۰۶ · از یافته تا توصیه'),
    cards: [
      [L('Beschreiben', 'Describe', 'توصیف'), L('Lokalisation, Anzahl, Dichte, mittleren Durchmesser und Morphologie dokumentieren. Bei teilsoliden Herden den soliden Anteil separat nennen; Voruntersuchung mit Datum und Veränderung angeben.', 'Document location, number, attenuation, mean diameter and morphology. Record the solid component separately in part-solid nodules, and state the prior examination date and interval change.', 'محل، تعداد، دانسیته، قطر میانگین و مورفولوژی را ثبت کنید. جزء جامد را جداگانه ذکر کنید و تاریخ بررسی قبلی و تغییرات را بنویسید.')],
      [L('Begründen', 'Explain', 'استدلال'), L('Anwendbarkeit und Risikokonstellation nennen, dann ein konkretes Zeitfenster empfehlen. „Kontrolle empfohlen“ allein ist zu ungenau. Bei fehlenden klinischen Angaben die Empfehlung daran knüpfen.', 'State eligibility and risk profile, then recommend a specific time window. “Follow-up recommended” alone is imprecise. Make recommendations conditional when clinical information is missing.', 'قابلیت کاربرد و وضعیت خطر را ذکر و سپس بازه زمانی مشخص پیشنهاد کنید. «پیگیری توصیه می‌شود» کافی نیست. اگر اطلاعات بالینی ناقص است توصیه را مشروط کنید.')],
    ],
    note: L('Beispielformulierung: „Solitärer solider Rundherd im rechten Unterlappen, mittlerer Durchmesser 7 mm, glatt begrenzt. Keine Voraufnahmen. Bei niedrigem klinischem Risiko und Anwendbarkeit der Fleischner-Empfehlungen 2017 Low-Dose-CT nach 6–12 Monaten; zusätzliche Kontrolle nach 18–24 Monaten erwägen.“', 'Example: “Solitary solid nodule in the right lower lobe, mean diameter 7 mm, smooth margins. No prior imaging. If clinical risk is low and Fleischner 2017 applies, low-dose CT at 6–12 months; consider additional CT at 18–24 months.”', 'مثال: «ندول جامد منفرد در لوب تحتانی راست، قطر میانگین ۷ میلی‌متر با حاشیه صاف. تصویر قبلی موجود نیست. در صورت خطر بالینی پایین و کاربرد توصیه‌های Fleischner ۲۰۱۷، CT کم‌دوز در ۶–۱۲ ماه؛ کنترل اضافی در ۱۸–۲۴ ماه قابل‌بررسی است.»') },
]

export const cases = [
  [L('52 Jahre · ein solider Herd, 5 mm · niedriges Risiko', 'Age 52 · one solid 5 mm nodule · low risk', '۵۲ سال · یک ندول جامد ۵ میلی‌متری · خطر پایین'), L('Welche Routinekontrolle ist vorgesehen?', 'What routine follow-up is indicated?', 'کدام پیگیری روتین لازم است؟'), L('Keine. Bei einem soliden Einzelherd <6 mm und niedrigem Risiko ist keine routinemäßige CT-Kontrolle vorgesehen.', 'None. A single solid nodule <6 mm in a low-risk patient requires no routine CT follow-up.', 'هیچ‌کدام. ندول جامد منفرد <۶ میلی‌متر در بیمار کم‌خطر به CT روتین نیاز ندارد.')],
  [L('68 Jahre · drei solide Herde, größter 7 mm · hohes Risiko', 'Age 68 · three solid nodules, largest 7 mm · high risk', '۶۸ سال · سه ندول جامد، بزرگ‌ترین ۷ میلی‌متر · خطر بالا'), L('Kein Herd besonders suspekt. Wann kontrollieren?', 'No particularly suspicious nodule. When is follow-up?', 'هیچ ندولی به‌طور خاص مشکوک نیست. چه زمانی پیگیری شود؟'), L('CT nach 3–6 und 18–24 Monaten. Bei multiplen soliden Herden beginnt die Kontrolle früher als beim solitären 6–8-mm-Herd.', 'CT at 3–6 and 18–24 months. Multiple solid nodules have an earlier initial follow-up than a solitary 6–8 mm nodule.', 'CT در ۳–۶ و ۱۸–۲۴ ماه. کنترل اولیه ندول‌های جامد متعدد زودتر از ندول منفرد ۶–۸ میلی‌متری است.')],
  [L('61 Jahre · reines Milchglas, 9 mm', 'Age 61 · pure ground glass, 9 mm', '۶۱ سال · شیشه‌مات خالص ۹ میلی‌متری'), L('Nach zwei Jahren stabil: Überwachung beenden?', 'Stable after two years: stop surveillance?', 'پس از دو سال ثابت است: پیگیری متوقف شود؟'), L('Nicht allein wegen zweijähriger Stabilität. Initial CT nach 6–12 Monaten, bei Persistenz alle 2 Jahre bis 5 Jahre. Subsolide Herde können langsam wachsen.', 'Not solely because of two-year stability. Initial CT at 6–12 months; if persistent, every 2 years until 5 years. Subsolid nodules may grow slowly.', 'صرفاً به دلیل ثبات دوساله خیر. CT اولیه در ۶–۱۲ ماه و در صورت ماندگاری هر ۲ سال تا ۵ سال. ندول نیمه‌جامد ممکن است آهسته رشد کند.')],
  [L('70 Jahre · persistierend teilsolide, 12 mm · solider Anteil 7 mm', 'Age 70 · persistent part-solid 12 mm nodule · solid component 7 mm', '۷۰ سال · ندول ماندگار بخشی جامد ۱۲ میلی‌متری · جزء جامد ۷ میلی‌متری'), L('Reicht die jährliche Routinekontrolle?', 'Is annual routine surveillance sufficient?', 'آیا پیگیری روتین سالانه کافی است؟'), L('Nein. Ein persistierender solider Anteil ≥6 mm ist hochgradig suspekt. Weitere Abklärung interdisziplinär festlegen; die jährliche Standardkontrolle setzt einen soliden Anteil <6 mm voraus.', 'No. A persistent solid component ≥6 mm is highly suspicious. Plan further work-up with the multidisciplinary team; the annual standard pathway requires a solid component <6 mm.', 'خیر. جزء جامد ماندگار ≥۶ میلی‌متر بسیار مشکوک است. بررسی تکمیلی را با تیم چندتخصصی تعیین کنید؛ مسیر استاندارد سالانه نیازمند جزء جامد <۶ میلی‌متر است.')],
  [L('59 Jahre · 6-mm-Herd im Lungenkrebs-Screening', 'Age 59 · 6 mm nodule on lung cancer screening', '۵۹ سال · ندول ۶ میلی‌متری در غربالگری سرطان ریه'), L('Welche Fleischner-Zeile passt?', 'Which Fleischner row applies?', 'کدام ردیف Fleischner کاربرد دارد؟'), L('Keine. Ein Screeningbefund wird nach dem jeweiligen Screening-System beurteilt, beispielsweise Lung-RADS. Erst den Anwendungskontext klären.', 'None. A screening finding is assessed under its screening system, such as Lung-RADS. Establish the clinical context first.', 'هیچ‌کدام. یافته غربالگری بر اساس سیستم مربوط مانند Lung-RADS ارزیابی می‌شود. ابتدا زمینه کاربرد را مشخص کنید.')],
]

export const takehome = [
  L('Erst Geltungsbereich, dann Tabelle.', 'Check scope before choosing a table.', 'پیش از جدول، دامنه کاربرد را بررسی کنید.'),
  L('Solide: 6 und 8 mm sind die zentralen Größengrenzen.', 'Solid nodules: 6 and 8 mm are the key size thresholds.', 'ندول جامد: ۶ و ۸ میلی‌متر آستانه‌های اصلی‌اند.'),
  L('Subsolide: Persistenz und solider Anteil bestimmen das Vorgehen.', 'Subsolid nodules: persistence and the solid component guide management.', 'نیمه‌جامد: ماندگاری و جزء جامد تعیین‌کننده‌اند.'),
  L('Multipel: Der suspekteste Herd führt.', 'Multiple nodules: the most suspicious one leads.', 'متعدد: مشکوک‌ترین ندول تعیین‌کننده است.'),
]
