export const MEDICATION_CATEGORIES = {
  thyroid: { fa: 'تیروئید', en: 'Thyroid' },
  bloodPressure: { fa: 'فشار خون', en: 'Blood pressure' },
  cholesterol: { fa: 'چربی خون', en: 'Cholesterol' },
  diabetes: { fa: 'دیابت', en: 'Diabetes' },
  antiplatelet: { fa: 'ضد پلاکت', en: 'Antiplatelet' },
  anticoagulant: { fa: 'ضد انعقاد', en: 'Anticoagulant' },
  stomach: { fa: 'معده و گوارش', en: 'Gastrointestinal' },
  mentalHealth: { fa: 'اعصاب و روان', en: 'Mental health' },
  neurology: { fa: 'مغز و اعصاب', en: 'Neurology' },
  pain: { fa: 'درد و التهاب', en: 'Pain and inflammation' },
  antibiotic: { fa: 'آنتی‌بیوتیک', en: 'Antibiotic' },
  supplement: { fa: 'مکمل', en: 'Supplement' },
  rheumatology: { fa: 'روماتولوژی', en: 'Rheumatology' },
  respiratory: { fa: 'تنفسی و آلرژی', en: 'Respiratory and allergy' },
  urology: { fa: 'اورولوژی', en: 'Urology' },
  cardiology: { fa: 'قلب', en: 'Cardiology' },
  weightManagement: { fa: 'کنترل وزن', en: 'Weight management' },
  womenHealth: { fa: 'سلامت زنان', en: "Women's health" },
  dermatology: { fa: 'پوست و مو', en: 'Dermatology' },
  ophthalmology: { fa: 'چشم', en: 'Ophthalmology' },
  natural: { fa: 'طبیعی و گیاهی', en: 'Natural and herbal' },
  other: { fa: 'سایر', en: 'Other' },
}

const OFFICIAL_SOURCES = {
  vitaminD: 'https://ods.od.nih.gov/factsheets/VitaminD-HealthProfessional/',
  iron: 'https://medlineplus.gov/ency/article/007478.htm',
  calcium: 'https://ods.od.nih.gov/factsheets/Calcium-Consumer/',
  multivitamin: 'https://ods.od.nih.gov/factsheets/MVMS-HealthProfessional/',
  magnesium: 'https://ods.od.nih.gov/factsheets/Magnesium-HealthProfessional/',
  omega3: 'https://ods.od.nih.gov/factsheets/Omega3FattyAcids-HealthProfessional/',
}

const GUIDANCE = {
  vitaminD: { text: 'ویتامین D معمولاً همراه غذایی که کمی چربی دارد بهتر جذب می‌شود.', suggestedRoutine: 'lunch', sourceUrl: OFFICIAL_SOURCES.vitaminD },
  iron: { text: 'آهن معمولاً با معدهٔ خالی بهتر جذب می‌شود. اگر معده‌ات اذیت شد، می‌توانی آن را با کمی غذا بخوری.', caution: 'هم‌زمان با شیر، کلسیم یا داروی ضداسید مصرف نکن؛ دست‌کم دو ساعت فاصله بده.', suggestedRoutine: 'fasting', sourceUrl: OFFICIAL_SOURCES.iron },
  calciumCarbonate: { text: 'کلسیم کربنات بهتر است همراه غذا مصرف شود.', caution: 'اگر مجموع مقدار روزانه زیاد است، دربارهٔ تقسیم آن به نوبت‌های ۵۰۰ میلی‌گرمی یا کمتر از پزشک یا داروساز بپرس.', suggestedRoutine: 'lunch', sourceUrl: OFFICIAL_SOURCES.calcium },
  calciumCitrate: { text: 'کلسیم سیترات را می‌توان با غذا یا بدون غذا مصرف کرد.', caution: 'اگر مقدار روزانه زیاد است، دربارهٔ تقسیم آن به نوبت‌های ۵۰۰ میلی‌گرمی یا کمتر از پزشک یا داروساز بپرس.', sourceUrl: OFFICIAL_SOURCES.calcium },
  multivitamin: { text: 'ترکیب مولتی‌ویتامین‌ها با هم فرق دارد؛ اول برچسب محصول را نگاه کن و آن را کنار یک وعدهٔ ثابت در برنامه بگذار.', suggestedRoutine: 'breakfast', sourceUrl: OFFICIAL_SOURCES.multivitamin },
  magnesium: { text: 'زمان ثابت و پیروی از برچسب محصول مهم‌تر از ساعت خاص است.', caution: 'مقدار زیاد منیزیمِ مکمل ممکن است دل‌پیچه، تهوع یا اسهال بدهد.', sourceUrl: OFFICIAL_SOURCES.magnesium },
  omega3: { text: 'ترکیب محصولات امگا۳ با هم فرق دارد؛ مقدار و زمان روی برچسب محصول را دنبال کن.', caution: 'اگر داروی رقیق‌کنندهٔ خون می‌خوری، پیش از مصرف با پزشک یا داروساز چک کن.', sourceUrl: OFFICIAL_SOURCES.omega3 },
  labelFirst: { text: 'زمان و مقدار مصرف این مکمل به ترکیب محصول بستگی دارد؛ برچسب همان محصول را دنبال کن.' },
  herbal: { text: 'ترکیب فرآورده‌های گیاهی یکسان نیست؛ مقدار و زمان روی برچسب همان محصول را دنبال کن.', caution: 'اگر داروی دیگری مصرف می‌کنی، دربارهٔ تداخل‌ها از پزشک یا داروساز بپرس.' },
}

export const MEDICATION_CATALOG = [
  { id: 'levothyroxine', fa: 'لووتیروکسین', en: 'Levothyroxine', category: 'thyroid', doses: ['۲۵ میکروگرم', '۵۰ میکروگرم', '۷۵ میکروگرم', '۱۰۰ میکروگرم', '۱۲۵ میکروگرم'] },
  { id: 'methimazole', fa: 'متی‌مازول', en: 'Methimazole', category: 'thyroid', doses: ['۵ میلی‌گرم', '۱۰ میلی‌گرم'] },
  { id: 'liothyronine', fa: 'لیوتیرونین', en: 'Liothyronine', category: 'thyroid', doses: ['۵ میکروگرم', '۲۵ میکروگرم', '۵۰ میکروگرم'] },
  { id: 'losartan', fa: 'لوزارتان', en: 'Losartan', category: 'bloodPressure', doses: ['۲۵ میلی‌گرم', '۵۰ میلی‌گرم', '۱۰۰ میلی‌گرم'] },
  { id: 'valsartan', fa: 'والزارتان', en: 'Valsartan', category: 'bloodPressure', doses: ['۴۰ میلی‌گرم', '۸۰ میلی‌گرم', '۱۶۰ میلی‌گرم', '۳۲۰ میلی‌گرم'] },
  { id: 'amlodipine', fa: 'آملودیپین', en: 'Amlodipine', category: 'bloodPressure', doses: ['۲٫۵ میلی‌گرم', '۵ میلی‌گرم', '۱۰ میلی‌گرم'] },
  { id: 'bisoprolol', fa: 'بیزوپرولول', en: 'Bisoprolol', category: 'bloodPressure', doses: ['۲٫۵ میلی‌گرم', '۵ میلی‌گرم', '۱۰ میلی‌گرم'] },
  { id: 'metoprolol', fa: 'متوپرولول', en: 'Metoprolol', category: 'bloodPressure', doses: ['۲۵ میلی‌گرم', '۵۰ میلی‌گرم', '۱۰۰ میلی‌گرم'] },
  { id: 'lisinopril', fa: 'لیزینوپریل', en: 'Lisinopril', category: 'bloodPressure', doses: ['۵ میلی‌گرم', '۱۰ میلی‌گرم', '۲۰ میلی‌گرم', '۴۰ میلی‌گرم'] },
  { id: 'ramipril', fa: 'رامیپریل', en: 'Ramipril', category: 'bloodPressure', doses: ['۲٫۵ میلی‌گرم', '۵ میلی‌گرم', '۱۰ میلی‌گرم'] },
  { id: 'hydrochlorothiazide', fa: 'هیدروکلروتیازید', en: 'Hydrochlorothiazide', category: 'bloodPressure', doses: ['۱۲٫۵ میلی‌گرم', '۲۵ میلی‌گرم', '۵۰ میلی‌گرم'] },
  { id: 'furosemide', fa: 'فوروزماید', en: 'Furosemide', category: 'bloodPressure', doses: ['۲۰ میلی‌گرم', '۴۰ میلی‌گرم', '۸۰ میلی‌گرم'] },
  { id: 'candesartan', fa: 'کاندسارتان', en: 'Candesartan', category: 'bloodPressure', doses: ['۴ میلی‌گرم', '۸ میلی‌گرم', '۱۶ میلی‌گرم', '۳۲ میلی‌گرم'] },
  { id: 'enalapril', fa: 'انالاپریل', en: 'Enalapril', category: 'bloodPressure', doses: ['۲٫۵ میلی‌گرم', '۵ میلی‌گرم', '۱۰ میلی‌گرم', '۲۰ میلی‌گرم'] },
  { id: 'propranolol', fa: 'پروپرانولول', en: 'Propranolol', category: 'bloodPressure', doses: ['۱۰ میلی‌گرم', '۲۰ میلی‌گرم', '۴۰ میلی‌گرم', '۸۰ میلی‌گرم'] },
  { id: 'carvedilol', fa: 'کارودیلول', en: 'Carvedilol', category: 'cardiology', doses: ['۳٫۱۲۵ میلی‌گرم', '۶٫۲۵ میلی‌گرم', '۱۲٫۵ میلی‌گرم', '۲۵ میلی‌گرم'] },
  { id: 'spironolactone', fa: 'اسپیرونولاکتون', en: 'Spironolactone', category: 'cardiology', doses: ['۲۵ میلی‌گرم', '۵۰ میلی‌گرم', '۱۰۰ میلی‌گرم'] },
  { id: 'digoxin', fa: 'دیگوکسین', en: 'Digoxin', category: 'cardiology', doses: ['۰٫۱۲۵ میلی‌گرم', '۰٫۲۵ میلی‌گرم'] },
  { id: 'nitroglycerin', fa: 'نیتروگلیسیرین', en: 'Nitroglycerin', category: 'cardiology', doses: ['۰٫۴ میلی‌گرم زیرزبانی', '۲٫۵ میلی‌گرم', '۶٫۴ میلی‌گرم'] },
  { id: 'atorvastatin', fa: 'آتورواستاتین', en: 'Atorvastatin', category: 'cholesterol', doses: ['۱۰ میلی‌گرم', '۲۰ میلی‌گرم', '۴۰ میلی‌گرم', '۸۰ میلی‌گرم'] },
  { id: 'rosuvastatin', fa: 'روزوواستاتین', en: 'Rosuvastatin', category: 'cholesterol', doses: ['۵ میلی‌گرم', '۱۰ میلی‌گرم', '۲۰ میلی‌گرم', '۴۰ میلی‌گرم'] },
  { id: 'ezetimibe', fa: 'ازتیمایب', en: 'Ezetimibe', category: 'cholesterol', doses: ['۱۰ میلی‌گرم'] },
  { id: 'simvastatin', fa: 'سیمواستاتین', en: 'Simvastatin', category: 'cholesterol', doses: ['۱۰ میلی‌گرم', '۲۰ میلی‌گرم', '۴۰ میلی‌گرم'] },
  { id: 'fenofibrate', fa: 'فنوفیبرات', en: 'Fenofibrate', category: 'cholesterol', doses: ['۴۸ میلی‌گرم', '۱۴۵ میلی‌گرم', '۱۶۰ میلی‌گرم'] },
  { id: 'metformin', fa: 'متفورمین', en: 'Metformin', category: 'diabetes', doses: ['۵۰۰ میلی‌گرم', '۸۵۰ میلی‌گرم', '۱۰۰۰ میلی‌گرم'] },
  { id: 'glimepiride', fa: 'گلیمپیرید', en: 'Glimepiride', category: 'diabetes', doses: ['۱ میلی‌گرم', '۲ میلی‌گرم', '۳ میلی‌گرم', '۴ میلی‌گرم'] },
  { id: 'sitagliptin', fa: 'سیتاگلیپتین', en: 'Sitagliptin', category: 'diabetes', doses: ['۲۵ میلی‌گرم', '۵۰ میلی‌گرم', '۱۰۰ میلی‌گرم'] },
  { id: 'empagliflozin', fa: 'امپاگلیفلوزین', en: 'Empagliflozin', category: 'diabetes', doses: ['۱۰ میلی‌گرم', '۲۵ میلی‌گرم'] },
  { id: 'insulin-glargine', fa: 'انسولین گلارژین', en: 'Insulin glargine', category: 'diabetes', doses: ['۱ واحد', '۱۰ واحد', '۲۰ واحد'] },
  { id: 'ozempic', fa: 'اوزمپیک', en: 'Ozempic (semaglutide)', aliases: ['ازمپیک', 'سمگلوتاید', 'Semaglutide'], category: 'diabetes', defaultFrequency: 'weekly', doses: ['۰٫۲۵ میلی‌گرم تزریقی', '۰٫۵ میلی‌گرم تزریقی', '۱ میلی‌گرم تزریقی', '۲ میلی‌گرم تزریقی'] },
  { id: 'mounjaro', fa: 'مانجارو', en: 'Mounjaro (tirzepatide)', aliases: ['مونجارو', 'تیرزپاتاید', 'Tirzepatide'], category: 'diabetes', defaultFrequency: 'weekly', doses: ['۲٫۵ میلی‌گرم تزریقی', '۵ میلی‌گرم تزریقی', '۷٫۵ میلی‌گرم تزریقی', '۱۰ میلی‌گرم تزریقی', '۱۲٫۵ میلی‌گرم تزریقی', '۱۵ میلی‌گرم تزریقی'] },
  { id: 'wegovy', fa: 'وگووی', en: 'Wegovy (semaglutide)', aliases: ['ویگووی', 'سمگلوتاید'], category: 'weightManagement', defaultFrequency: 'weekly', doses: ['۰٫۲۵ میلی‌گرم تزریقی', '۰٫۵ میلی‌گرم تزریقی', '۱ میلی‌گرم تزریقی', '۱٫۷ میلی‌گرم تزریقی', '۲٫۴ میلی‌گرم تزریقی'] },
  { id: 'gliclazide', fa: 'گلیکلازید', en: 'Gliclazide', category: 'diabetes', doses: ['۳۰ میلی‌گرم', '۶۰ میلی‌گرم', '۸۰ میلی‌گرم'] },
  { id: 'dapagliflozin', fa: 'داپاگلیفلوزین', en: 'Dapagliflozin', category: 'diabetes', doses: ['۵ میلی‌گرم', '۱۰ میلی‌گرم'] },
  { id: 'linagliptin', fa: 'لیناگلیپتین', en: 'Linagliptin', category: 'diabetes', doses: ['۵ میلی‌گرم'] },
  { id: 'insulin-aspart', fa: 'انسولین آسپارت', en: 'Insulin aspart', category: 'diabetes', doses: ['۱ واحد', '۵ واحد', '۱۰ واحد'] },
  { id: 'aspirin', fa: 'آسپرین', en: 'Aspirin', category: 'antiplatelet', doses: ['۸۰ میلی‌گرم', '۱۰۰ میلی‌گرم', '۳۲۵ میلی‌گرم'] },
  { id: 'clopidogrel', fa: 'کلوپیدوگرل', en: 'Clopidogrel', category: 'antiplatelet', doses: ['۷۵ میلی‌گرم'] },
  { id: 'warfarin', fa: 'وارفارین', en: 'Warfarin', category: 'anticoagulant', doses: ['۱ میلی‌گرم', '۲ میلی‌گرم', '۲٫۵ میلی‌گرم', '۵ میلی‌گرم'] },
  { id: 'apixaban', fa: 'آپیکسابان', en: 'Apixaban', category: 'anticoagulant', doses: ['۲٫۵ میلی‌گرم', '۵ میلی‌گرم'] },
  { id: 'rivaroxaban', fa: 'ریواروکسابان', en: 'Rivaroxaban', category: 'anticoagulant', doses: ['۲٫۵ میلی‌گرم', '۱۰ میلی‌گرم', '۱۵ میلی‌گرم', '۲۰ میلی‌گرم'] },
  { id: 'dabigatran', fa: 'دابیگاتران', en: 'Dabigatran', category: 'anticoagulant', doses: ['۷۵ میلی‌گرم', '۱۱۰ میلی‌گرم', '۱۵۰ میلی‌گرم'] },
  { id: 'omeprazole', fa: 'امپرازول', en: 'Omeprazole', category: 'stomach', doses: ['۲۰ میلی‌گرم', '۴۰ میلی‌گرم'] },
  { id: 'pantoprazole', fa: 'پنتوپرازول', en: 'Pantoprazole', category: 'stomach', doses: ['۲۰ میلی‌گرم', '۴۰ میلی‌گرم'] },
  { id: 'famotidine', fa: 'فاموتیدین', en: 'Famotidine', category: 'stomach', doses: ['۲۰ میلی‌گرم', '۴۰ میلی‌گرم'] },
  { id: 'esomeprazole', fa: 'ازومپرازول', en: 'Esomeprazole', category: 'stomach', doses: ['۲۰ میلی‌گرم', '۴۰ میلی‌گرم'] },
  { id: 'metoclopramide', fa: 'متوکلوپرامید', en: 'Metoclopramide', category: 'stomach', doses: ['۵ میلی‌گرم', '۱۰ میلی‌گرم'] },
  { id: 'ondansetron', fa: 'اندانسترون', en: 'Ondansetron', category: 'stomach', doses: ['۴ میلی‌گرم', '۸ میلی‌گرم'] },
  { id: 'mesalamine', fa: 'مسالازین', en: 'Mesalamine', category: 'stomach', doses: ['۴۰۰ میلی‌گرم', '۸۰۰ میلی‌گرم', '۱٫۲ گرم'] },
  { id: 'sertraline', fa: 'سرترالین', en: 'Sertraline', category: 'mentalHealth', doses: ['۲۵ میلی‌گرم', '۵۰ میلی‌گرم', '۱۰۰ میلی‌گرم'] },
  { id: 'escitalopram', fa: 'اس‌سیتالوپرام', en: 'Escitalopram', category: 'mentalHealth', doses: ['۵ میلی‌گرم', '۱۰ میلی‌گرم', '۲۰ میلی‌گرم'] },
  { id: 'fluoxetine', fa: 'فلوکستین', en: 'Fluoxetine', category: 'mentalHealth', doses: ['۱۰ میلی‌گرم', '۲۰ میلی‌گرم', '۴۰ میلی‌گرم'] },
  { id: 'venlafaxine', fa: 'ونلافاکسین', en: 'Venlafaxine', category: 'mentalHealth', doses: ['۳۷٫۵ میلی‌گرم', '۷۵ میلی‌گرم', '۱۵۰ میلی‌گرم'] },
  { id: 'duloxetine', fa: 'دولوکستین', en: 'Duloxetine', category: 'mentalHealth', doses: ['۲۰ میلی‌گرم', '۳۰ میلی‌گرم', '۶۰ میلی‌گرم'] },
  { id: 'bupropion', fa: 'بوپروپیون', en: 'Bupropion', category: 'mentalHealth', doses: ['۷۵ میلی‌گرم', '۱۰۰ میلی‌گرم', '۱۵۰ میلی‌گرم', '۳۰۰ میلی‌گرم'] },
  { id: 'mirtazapine', fa: 'میرتازاپین', en: 'Mirtazapine', category: 'mentalHealth', doses: ['۷٫۵ میلی‌گرم', '۱۵ میلی‌گرم', '۳۰ میلی‌گرم', '۴۵ میلی‌گرم'] },
  { id: 'quetiapine', fa: 'کوتیاپین', en: 'Quetiapine', category: 'mentalHealth', doses: ['۲۵ میلی‌گرم', '۵۰ میلی‌گرم', '۱۰۰ میلی‌گرم', '۲۰۰ میلی‌گرم'] },
  { id: 'risperidone', fa: 'ریسپریدون', en: 'Risperidone', category: 'mentalHealth', doses: ['۰٫۵ میلی‌گرم', '۱ میلی‌گرم', '۲ میلی‌گرم', '۴ میلی‌گرم'] },
  { id: 'gabapentin', fa: 'گاباپنتین', en: 'Gabapentin', category: 'neurology', doses: ['۱۰۰ میلی‌گرم', '۳۰۰ میلی‌گرم', '۴۰۰ میلی‌گرم', '۶۰۰ میلی‌گرم'] },
  { id: 'pregabalin', fa: 'پرگابالین', en: 'Pregabalin', category: 'neurology', doses: ['۲۵ میلی‌گرم', '۵۰ میلی‌گرم', '۷۵ میلی‌گرم', '۱۵۰ میلی‌گرم'] },
  { id: 'levetiracetam', fa: 'لوتیراستام', en: 'Levetiracetam', category: 'neurology', doses: ['۲۵۰ میلی‌گرم', '۵۰۰ میلی‌گرم', '۷۵۰ میلی‌گرم', '۱۰۰۰ میلی‌گرم'] },
  { id: 'lamotrigine', fa: 'لاموتریژین', en: 'Lamotrigine', category: 'neurology', doses: ['۲۵ میلی‌گرم', '۵۰ میلی‌گرم', '۱۰۰ میلی‌گرم', '۲۰۰ میلی‌گرم'] },
  { id: 'carbamazepine', fa: 'کاربامازپین', en: 'Carbamazepine', category: 'neurology', doses: ['۱۰۰ میلی‌گرم', '۲۰۰ میلی‌گرم', '۴۰۰ میلی‌گرم'] },
  { id: 'valproate', fa: 'والپروات سدیم', en: 'Sodium valproate', category: 'neurology', doses: ['۲۰۰ میلی‌گرم', '۳۰۰ میلی‌گرم', '۵۰۰ میلی‌گرم'] },
  { id: 'topiramate', fa: 'توپیرامات', en: 'Topiramate', category: 'neurology', doses: ['۲۵ میلی‌گرم', '۵۰ میلی‌گرم', '۱۰۰ میلی‌گرم', '۲۰۰ میلی‌گرم'] },
  { id: 'donepezil', fa: 'دونپزیل', en: 'Donepezil', category: 'neurology', doses: ['۵ میلی‌گرم', '۱۰ میلی‌گرم', '۲۳ میلی‌گرم'] },
  { id: 'levodopa-carbidopa', fa: 'لوودوپا / کاربیدوپا', en: 'Levodopa / carbidopa', category: 'neurology', doses: ['۱۰۰/۲۵ میلی‌گرم', '۲۰۰/۵۰ میلی‌گرم'] },
  { id: 'acetaminophen', fa: 'استامینوفن', en: 'Acetaminophen', category: 'pain', doses: ['۳۲۵ میلی‌گرم', '۵۰۰ میلی‌گرم', '۶۵۰ میلی‌گرم'] },
  { id: 'ibuprofen', fa: 'ایبوپروفن', en: 'Ibuprofen', category: 'pain', doses: ['۲۰۰ میلی‌گرم', '۴۰۰ میلی‌گرم', '۶۰۰ میلی‌گرم'] },
  { id: 'naproxen', fa: 'ناپروکسن', en: 'Naproxen', category: 'pain', doses: ['۲۵۰ میلی‌گرم', '۵۰۰ میلی‌گرم'] },
  { id: 'diclofenac', fa: 'دیکلوفناک', en: 'Diclofenac', category: 'pain', doses: ['۲۵ میلی‌گرم', '۵۰ میلی‌گرم', '۷۵ میلی‌گرم'] },
  { id: 'celecoxib', fa: 'سلکوکسیب', en: 'Celecoxib', category: 'pain', doses: ['۱۰۰ میلی‌گرم', '۲۰۰ میلی‌گرم'] },
  { id: 'tramadol', fa: 'ترامادول', en: 'Tramadol', category: 'pain', doses: ['۵۰ میلی‌گرم', '۱۰۰ میلی‌گرم'] },
  { id: 'baclofen', fa: 'باکلوفن', en: 'Baclofen', category: 'pain', doses: ['۵ میلی‌گرم', '۱۰ میلی‌گرم', '۲۰ میلی‌گرم'] },
  { id: 'amoxicillin', fa: 'آموکسی‌سیلین', en: 'Amoxicillin', category: 'antibiotic', doses: ['۲۵۰ میلی‌گرم', '۵۰۰ میلی‌گرم', '۸۷۵ میلی‌گرم'] },
  { id: 'azithromycin', fa: 'آزیترومایسین', en: 'Azithromycin', category: 'antibiotic', doses: ['۲۵۰ میلی‌گرم', '۵۰۰ میلی‌گرم'] },
  { id: 'cefuroxime', fa: 'سفوروکسیم', en: 'Cefuroxime', category: 'antibiotic', doses: ['۲۵۰ میلی‌گرم', '۵۰۰ میلی‌گرم'] },
  { id: 'cephalexin', fa: 'سفالکسین', en: 'Cephalexin', category: 'antibiotic', doses: ['۲۵۰ میلی‌گرم', '۵۰۰ میلی‌گرم'] },
  { id: 'ciprofloxacin', fa: 'سیپروفلوکساسین', en: 'Ciprofloxacin', category: 'antibiotic', doses: ['۲۵۰ میلی‌گرم', '۵۰۰ میلی‌گرم', '۷۵۰ میلی‌گرم'] },
  { id: 'doxycycline', fa: 'داکسی‌سایکلین', en: 'Doxycycline', category: 'antibiotic', doses: ['۵۰ میلی‌گرم', '۱۰۰ میلی‌گرم'] },
  { id: 'metronidazole', fa: 'مترونیدازول', en: 'Metronidazole', category: 'antibiotic', doses: ['۲۵۰ میلی‌گرم', '۵۰۰ میلی‌گرم'] },
  { id: 'multivitamin', fa: 'مولتی‌ویتامین', en: 'Multivitamin', category: 'supplement', doses: ['۱ قرص', '۱ کپسول', '۵ میلی‌لیتر'], guidance: GUIDANCE.multivitamin },
  { id: 'prenatal-multivitamin', fa: 'مولتی‌ویتامین بارداری', en: 'Prenatal multivitamin', category: 'supplement', doses: ['۱ قرص', '۱ کپسول'], guidance: GUIDANCE.multivitamin },
  { id: 'vitamin-d3', fa: 'ویتامین د۳', en: 'Vitamin D3', aliases: ['ویتامین دی', 'ویتامین D'], category: 'supplement', doses: ['۴۰۰ واحد', '۱۰۰۰ واحد', '۲۰۰۰ واحد', '۵۰۰۰ واحد', '۵۰۰۰۰ واحد'], guidance: GUIDANCE.vitaminD },
  { id: 'vitamin-c', fa: 'ویتامین C', en: 'Vitamin C', category: 'supplement', doses: ['۲۵۰ میلی‌گرم', '۵۰۰ میلی‌گرم', '۱۰۰۰ میلی‌گرم'], guidance: GUIDANCE.labelFirst },
  { id: 'vitamin-b-complex', fa: 'ویتامین ب کمپلکس', en: 'Vitamin B complex', category: 'supplement', doses: ['۱ قرص', '۱ کپسول'], guidance: GUIDANCE.labelFirst },
  { id: 'vitamin-b12', fa: 'ویتامین ب۱۲', en: 'Vitamin B12', category: 'supplement', doses: ['۲۵۰ میکروگرم', '۵۰۰ میکروگرم', '۱۰۰۰ میکروگرم'], guidance: GUIDANCE.labelFirst },
  { id: 'folic-acid', fa: 'فولیک اسید', en: 'Folic acid', category: 'supplement', doses: ['۴۰۰ میکروگرم', '۸۰۰ میکروگرم', '۱ میلی‌گرم', '۵ میلی‌گرم'], guidance: GUIDANCE.labelFirst },
  { id: 'vitamin-e', fa: 'ویتامین E', en: 'Vitamin E', category: 'supplement', doses: ['۱۰۰ واحد', '۲۰۰ واحد', '۴۰۰ واحد'], guidance: GUIDANCE.labelFirst },
  { id: 'vitamin-k2', fa: 'ویتامین K2', en: 'Vitamin K2', category: 'supplement', doses: ['۴۵ میکروگرم', '۹۰ میکروگرم', '۱۰۰ میکروگرم'], guidance: GUIDANCE.labelFirst },
  { id: 'iron', fa: 'آهن', en: 'Iron', category: 'supplement', doses: ['۱۸ میلی‌گرم', '۲۷ میلی‌گرم', '۶۵ میلی‌گرم'], guidance: GUIDANCE.iron },
  { id: 'ferrous-sulfate', fa: 'فروس سولفات', en: 'Ferrous sulfate', category: 'supplement', doses: ['۳۲۵ میلی‌گرم'], guidance: GUIDANCE.iron },
  { id: 'calcium-carbonate', fa: 'کلسیم کربنات', en: 'Calcium carbonate', category: 'supplement', doses: ['۵۰۰ میلی‌گرم', '۶۰۰ میلی‌گرم'], guidance: GUIDANCE.calciumCarbonate },
  { id: 'calcium-citrate', fa: 'کلسیم سیترات', en: 'Calcium citrate', category: 'supplement', doses: ['۲۵۰ میلی‌گرم', '۵۰۰ میلی‌گرم'], guidance: GUIDANCE.calciumCitrate },
  { id: 'magnesium', fa: 'منیزیم', en: 'Magnesium', category: 'supplement', doses: ['۱۰۰ میلی‌گرم', '۲۰۰ میلی‌گرم', '۲۵۰ میلی‌گرم', '۴۰۰ میلی‌گرم'], guidance: GUIDANCE.magnesium },
  { id: 'zinc', fa: 'زینک (روی)', en: 'Zinc', category: 'supplement', doses: ['۱۰ میلی‌گرم', '۱۵ میلی‌گرم', '۲۵ میلی‌گرم', '۵۰ میلی‌گرم'], guidance: GUIDANCE.labelFirst },
  { id: 'selenium', fa: 'سلنیوم', en: 'Selenium', category: 'supplement', doses: ['۵۰ میکروگرم', '۱۰۰ میکروگرم', '۲۰۰ میکروگرم'], guidance: GUIDANCE.labelFirst },
  { id: 'omega-3', fa: 'امگا ۳', en: 'Omega-3 / fish oil', category: 'supplement', doses: ['۵۰۰ میلی‌گرم', '۱۰۰۰ میلی‌گرم', '۱۲۰۰ میلی‌گرم'], guidance: GUIDANCE.omega3 },
  { id: 'coq10', fa: 'کوآنزیم Q10', en: 'Coenzyme Q10', category: 'supplement', doses: ['۳۰ میلی‌گرم', '۱۰۰ میلی‌گرم', '۲۰۰ میلی‌گرم'], guidance: GUIDANCE.labelFirst },
  { id: 'probiotic', fa: 'پروبیوتیک', en: 'Probiotic', category: 'supplement', doses: ['۱ کپسول', '۱ ساشه'], guidance: GUIDANCE.labelFirst },
  { id: 'biotin', fa: 'بیوتین', en: 'Biotin', category: 'supplement', doses: ['۱۰۰۰ میکروگرم', '۵۰۰۰ میکروگرم', '۱۰۰۰۰ میکروگرم'], guidance: GUIDANCE.labelFirst },
  { id: 'collagen', fa: 'کلاژن', en: 'Collagen', category: 'supplement', doses: ['۱ پیمانه', '۵ گرم', '۱۰ گرم'], guidance: GUIDANCE.labelFirst },
  { id: 'glucosamine-chondroitin', fa: 'گلوکزامین کندرویتین', en: 'Glucosamine chondroitin', category: 'supplement', doses: ['۱ قرص', '۱ کپسول'], guidance: GUIDANCE.labelFirst },
  { id: 'prednisolone', fa: 'پردنیزولون', en: 'Prednisolone', category: 'rheumatology', doses: ['۵ میلی‌گرم', '۱۰ میلی‌گرم', '۲۰ میلی‌گرم'] },
  { id: 'methotrexate', fa: 'متوترکسات', en: 'Methotrexate', category: 'rheumatology', doses: ['۲٫۵ میلی‌گرم', '۱۰ میلی‌گرم'] },
  { id: 'hydroxychloroquine', fa: 'هیدروکسی‌کلروکین', en: 'Hydroxychloroquine', category: 'rheumatology', doses: ['۲۰۰ میلی‌گرم'] },
  { id: 'tamsulosin', fa: 'تامسولوسین', en: 'Tamsulosin', category: 'urology', doses: ['۰٫۴ میلی‌گرم'] },
  { id: 'finasteride', fa: 'فیناستراید', en: 'Finasteride', category: 'urology', doses: ['۱ میلی‌گرم', '۵ میلی‌گرم'] },
  { id: 'dutasteride', fa: 'دوتاستراید', en: 'Dutasteride', category: 'urology', doses: ['۰٫۵ میلی‌گرم'] },
  { id: 'solifenacin', fa: 'سولیفناسین', en: 'Solifenacin', category: 'urology', doses: ['۵ میلی‌گرم', '۱۰ میلی‌گرم'] },
  { id: 'montelukast', fa: 'مونته‌لوکاست', en: 'Montelukast', category: 'respiratory', doses: ['۴ میلی‌گرم', '۵ میلی‌گرم', '۱۰ میلی‌گرم'] },
  { id: 'cetirizine', fa: 'ستیریزین', en: 'Cetirizine', category: 'respiratory', doses: ['۵ میلی‌گرم', '۱۰ میلی‌گرم'] },
  { id: 'loratadine', fa: 'لوراتادین', en: 'Loratadine', category: 'respiratory', doses: ['۱۰ میلی‌گرم'] },
  { id: 'fexofenadine', fa: 'فکسوفنادین', en: 'Fexofenadine', category: 'respiratory', doses: ['۶۰ میلی‌گرم', '۱۲۰ میلی‌گرم', '۱۸۰ میلی‌گرم'] },
  { id: 'salbutamol', fa: 'سالبوتامول', en: 'Salbutamol / albuterol', category: 'respiratory', doses: ['۱ پاف', '۲ پاف', '۲ میلی‌گرم', '۴ میلی‌گرم'] },
  { id: 'budesonide-inhaler', fa: 'بودزوناید استنشاقی', en: 'Budesonide inhaler', category: 'respiratory', doses: ['۱۰۰ میکروگرم', '۲۰۰ میکروگرم', '۴۰۰ میکروگرم'] },
  { id: 'fluticasone-nasal', fa: 'فلوتیکازون بینی', en: 'Fluticasone nasal spray', category: 'respiratory', doses: ['۱ پاف', '۲ پاف'] },
  { id: 'alendronate', fa: 'آلندرونیت', en: 'Alendronate', category: 'rheumatology', doses: ['۱۰ میلی‌گرم', '۷۰ میلی‌گرم'] },
  { id: 'letrozole', fa: 'لتروزول', en: 'Letrozole', category: 'womenHealth', doses: ['۲٫۵ میلی‌گرم'] },
  { id: 'estradiol', fa: 'استرادیول', en: 'Estradiol', category: 'womenHealth', doses: ['۰٫۵ میلی‌گرم', '۱ میلی‌گرم', '۲ میلی‌گرم'] },
  { id: 'progesterone', fa: 'پروژسترون', en: 'Progesterone', category: 'womenHealth', doses: ['۱۰۰ میلی‌گرم', '۲۰۰ میلی‌گرم'] },
  { id: 'isotretinoin', fa: 'ایزوترتینوئین', en: 'Isotretinoin', category: 'dermatology', doses: ['۱۰ میلی‌گرم', '۲۰ میلی‌گرم', '۴۰ میلی‌گرم'] },
  { id: 'minoxidil', fa: 'ماینوکسیدیل', en: 'Minoxidil topical', category: 'dermatology', doses: ['۲ درصد', '۵ درصد'] },
  { id: 'cetirizine-skin', fa: 'هیدروکسی‌زین', en: 'Hydroxyzine', category: 'dermatology', doses: ['۱۰ میلی‌گرم', '۲۵ میلی‌گرم', '۵۰ میلی‌گرم'] },
  { id: 'latanoprost', fa: 'لاتانوپروست', en: 'Latanoprost eye drops', category: 'ophthalmology', doses: ['۱ قطره'] },
  { id: 'timolol-eye', fa: 'تیمولول چشمی', en: 'Timolol eye drops', category: 'ophthalmology', doses: ['۰٫۲۵ درصد', '۰٫۵ درصد'] },
  { id: 'artificial-tears', fa: 'اشک مصنوعی', en: 'Artificial tears', category: 'ophthalmology', doses: ['۱ قطره', '۲ قطره'] },
  { id: 'turmeric', fa: 'زردچوبه / کورکومین', en: 'Turmeric / curcumin', category: 'natural', doses: ['۱ کپسول', '۵۰۰ میلی‌گرم', '۱۰۰۰ میلی‌گرم'], guidance: GUIDANCE.herbal },
  { id: 'ginger', fa: 'زنجبیل', en: 'Ginger supplement', category: 'natural', doses: ['۱ کپسول', '۵۰۰ میلی‌گرم', '۱۰۰۰ میلی‌گرم'], guidance: GUIDANCE.herbal },
  { id: 'garlic', fa: 'مکمل سیر', en: 'Garlic supplement', category: 'natural', doses: ['۱ قرص', '۵۰۰ میلی‌گرم', '۱۰۰۰ میلی‌گرم'], guidance: GUIDANCE.herbal },
  { id: 'valerian', fa: 'سنبل‌الطیب', en: 'Valerian', category: 'natural', doses: ['۱ کپسول', '۳۰۰ میلی‌گرم', '۵۰۰ میلی‌گرم'], guidance: GUIDANCE.herbal },
  { id: 'milk-thistle', fa: 'خار مریم', en: 'Milk thistle', category: 'natural', doses: ['۱ کپسول', '۱۴۰ میلی‌گرم'], guidance: GUIDANCE.herbal },
  { id: 'echinacea', fa: 'اکیناسه', en: 'Echinacea', category: 'natural', doses: ['۱ کپسول', '۵۰۰ میلی‌گرم'], guidance: GUIDANCE.herbal },
  { id: 'ginkgo', fa: 'جینکو بیلوبا', en: 'Ginkgo biloba', category: 'natural', doses: ['۴۰ میلی‌گرم', '۱۲۰ میلی‌گرم'], guidance: GUIDANCE.herbal },
  { id: 'ginseng', fa: 'جینسینگ', en: 'Ginseng', category: 'natural', doses: ['۱ کپسول', '۲۰۰ میلی‌گرم', '۴۰۰ میلی‌گرم'], guidance: GUIDANCE.herbal },
  { id: 'saw-palmetto', fa: 'ساو پالمتو', en: 'Saw palmetto', category: 'natural', doses: ['۱۶۰ میلی‌گرم', '۳۲۰ میلی‌گرم'], guidance: GUIDANCE.herbal },
  { id: 'propylthiouracil', fa: 'پروپیل‌تیواوراسیل', en: 'Propylthiouracil (PTU)', aliases: ['PTU'], category: 'thyroid', doses: ['۵۰ میلی‌گرم'] },
  { id: 'irbesartan', fa: 'ایربسارتان', en: 'Irbesartan', category: 'bloodPressure', doses: ['۷۵ میلی‌گرم', '۱۵۰ میلی‌گرم', '۳۰۰ میلی‌گرم'] },
  { id: 'telmisartan', fa: 'تلمیسارتان', en: 'Telmisartan', category: 'bloodPressure', doses: ['۲۰ میلی‌گرم', '۴۰ میلی‌گرم', '۸۰ میلی‌گرم'] },
  { id: 'olmesartan', fa: 'اولمسارتان', en: 'Olmesartan', category: 'bloodPressure', doses: ['۵ میلی‌گرم', '۱۰ میلی‌گرم', '۲۰ میلی‌گرم', '۴۰ میلی‌گرم'] },
  { id: 'nifedipine', fa: 'نیفدیپین', en: 'Nifedipine', category: 'bloodPressure', doses: ['۱۰ میلی‌گرم', '۲۰ میلی‌گرم', '۳۰ میلی‌گرم', '۶۰ میلی‌گرم'] },
  { id: 'diltiazem', fa: 'دیلتیازم', en: 'Diltiazem', category: 'cardiology', doses: ['۳۰ میلی‌گرم', '۶۰ میلی‌گرم', '۹۰ میلی‌گرم', '۱۲۰ میلی‌گرم', '۱۸۰ میلی‌گرم', '۲۴۰ میلی‌گرم'] },
  { id: 'verapamil', fa: 'وراپامیل', en: 'Verapamil', category: 'cardiology', doses: ['۴۰ میلی‌گرم', '۸۰ میلی‌گرم', '۱۲۰ میلی‌گرم', '۲۴۰ میلی‌گرم'] },
  { id: 'nebivolol', fa: 'نبیوولول', en: 'Nebivolol', category: 'bloodPressure', doses: ['۲٫۵ میلی‌گرم', '۵ میلی‌گرم', '۱۰ میلی‌گرم'] },
  { id: 'indapamide', fa: 'اینداپامید', en: 'Indapamide', category: 'bloodPressure', doses: ['۱٫۵ میلی‌گرم', '۲٫۵ میلی‌گرم'] },
  { id: 'torsemide', fa: 'تورسماید', en: 'Torsemide', aliases: ['Torasemide'], category: 'cardiology', doses: ['۵ میلی‌گرم', '۱۰ میلی‌گرم', '۲۰ میلی‌گرم', '۴۰ میلی‌گرم'] },
  { id: 'sacubitril-valsartan', fa: 'ساکوبیتریل / والزارتان', en: 'Sacubitril / valsartan', aliases: ['Entresto', 'انترستو'], category: 'cardiology', doses: ['۲۴/۲۶ میلی‌گرم', '۴۹/۵۱ میلی‌گرم', '۹۷/۱۰۳ میلی‌گرم'] },
  { id: 'amiodarone', fa: 'آمیودارون', en: 'Amiodarone', category: 'cardiology', doses: ['۱۰۰ میلی‌گرم', '۲۰۰ میلی‌گرم'] },
  { id: 'ivabradine', fa: 'ایوابرادین', en: 'Ivabradine', category: 'cardiology', doses: ['۲٫۵ میلی‌گرم', '۵ میلی‌گرم', '۷٫۵ میلی‌گرم'] },
  { id: 'isosorbide-mononitrate', fa: 'ایزوسورباید مونونیترات', en: 'Isosorbide mononitrate', category: 'cardiology', doses: ['۱۰ میلی‌گرم', '۲۰ میلی‌گرم', '۳۰ میلی‌گرم', '۶۰ میلی‌گرم'] },
  { id: 'pravastatin', fa: 'پراواستاتین', en: 'Pravastatin', category: 'cholesterol', doses: ['۱۰ میلی‌گرم', '۲۰ میلی‌گرم', '۴۰ میلی‌گرم', '۸۰ میلی‌گرم'] },
  { id: 'fluvastatin', fa: 'فلوواستاتین', en: 'Fluvastatin', category: 'cholesterol', doses: ['۲۰ میلی‌گرم', '۴۰ میلی‌گرم', '۸۰ میلی‌گرم'] },
  { id: 'gemfibrozil', fa: 'جم‌فیبروزیل', en: 'Gemfibrozil', category: 'cholesterol', doses: ['۶۰۰ میلی‌گرم'] },
  { id: 'pioglitazone', fa: 'پیوگلیتازون', en: 'Pioglitazone', category: 'diabetes', doses: ['۱۵ میلی‌گرم', '۳۰ میلی‌گرم', '۴۵ میلی‌گرم'] },
  { id: 'repaglinide', fa: 'رپاگلیناید', en: 'Repaglinide', category: 'diabetes', doses: ['۰٫۵ میلی‌گرم', '۱ میلی‌گرم', '۲ میلی‌گرم'] },
  { id: 'dulaglutide', fa: 'ترولیسیتی', en: 'Trulicity (dulaglutide)', aliases: ['دولاگلوتاید', 'Trulicity'], category: 'diabetes', defaultFrequency: 'weekly', doses: ['۰٫۷۵ میلی‌گرم تزریقی', '۱٫۵ میلی‌گرم تزریقی', '۳ میلی‌گرم تزریقی', '۴٫۵ میلی‌گرم تزریقی'] },
  { id: 'liraglutide', fa: 'ویکتوزا', en: 'Victoza (liraglutide)', aliases: ['لیراگلوتاید', 'Victoza'], category: 'diabetes', doses: ['۰٫۶ میلی‌گرم تزریقی', '۱٫۲ میلی‌گرم تزریقی', '۱٫۸ میلی‌گرم تزریقی'] },
  { id: 'insulin-degludec', fa: 'انسولین دگلودک', en: 'Insulin degludec', aliases: ['Tresiba', 'ترسیبا'], category: 'diabetes', doses: ['۱ واحد', '۵ واحد', '۱۰ واحد', '۲۰ واحد'] },
  { id: 'insulin-lispro', fa: 'انسولین لیسپرو', en: 'Insulin lispro', aliases: ['Humalog', 'هومالوگ'], category: 'diabetes', doses: ['۱ واحد', '۵ واحد', '۱۰ واحد'] },
  { id: 'regular-insulin', fa: 'انسولین رگولار', en: 'Regular insulin', category: 'diabetes', doses: ['۱ واحد', '۵ واحد', '۱۰ واحد'] },
  { id: 'ticagrelor', fa: 'تیکاگرلور', en: 'Ticagrelor', aliases: ['Brilique', 'Brilinta'], category: 'antiplatelet', doses: ['۶۰ میلی‌گرم', '۹۰ میلی‌گرم'] },
  { id: 'prasugrel', fa: 'پراسوگرل', en: 'Prasugrel', category: 'antiplatelet', doses: ['۵ میلی‌گرم', '۱۰ میلی‌گرم'] },
  { id: 'edoxaban', fa: 'ادوکسابان', en: 'Edoxaban', aliases: ['Lixiana'], category: 'anticoagulant', doses: ['۱۵ میلی‌گرم', '۳۰ میلی‌گرم', '۶۰ میلی‌گرم'] },
  { id: 'enoxaparin', fa: 'انوکساپارین', en: 'Enoxaparin', aliases: ['Clexane', 'کلکسان'], category: 'anticoagulant', doses: ['۲۰ میلی‌گرم تزریقی', '۴۰ میلی‌گرم تزریقی', '۶۰ میلی‌گرم تزریقی', '۸۰ میلی‌گرم تزریقی', '۱۰۰ میلی‌گرم تزریقی'] },
  { id: 'lansoprazole', fa: 'لانسوپرازول', en: 'Lansoprazole', category: 'stomach', doses: ['۱۵ میلی‌گرم', '۳۰ میلی‌گرم'] },
  { id: 'rabeprazole', fa: 'رابپرازول', en: 'Rabeprazole', category: 'stomach', doses: ['۱۰ میلی‌گرم', '۲۰ میلی‌گرم'] },
  { id: 'domperidone', fa: 'دومپریدون', en: 'Domperidone', category: 'stomach', doses: ['۱۰ میلی‌گرم'] },
  { id: 'loperamide', fa: 'لوپرامید', en: 'Loperamide', category: 'stomach', doses: ['۲ میلی‌گرم'] },
  { id: 'lactulose', fa: 'لاکتولوز', en: 'Lactulose', category: 'stomach', doses: ['۵ میلی‌لیتر', '۱۰ میلی‌لیتر', '۱۵ میلی‌لیتر', '۳۰ میلی‌لیتر'] },
  { id: 'bisacodyl', fa: 'بیزاکودیل', en: 'Bisacodyl', category: 'stomach', doses: ['۵ میلی‌گرم', '۱۰ میلی‌گرم'] },
  { id: 'macrogol', fa: 'ماکروگول', en: 'Macrogol / polyethylene glycol', aliases: ['PEG'], category: 'stomach', doses: ['۱ ساشه'] },
  { id: 'dicyclomine', fa: 'دای‌سیکلومین', en: 'Dicyclomine', category: 'stomach', doses: ['۱۰ میلی‌گرم', '۲۰ میلی‌گرم'] },
  { id: 'citalopram', fa: 'سیتالوپرام', en: 'Citalopram', category: 'mentalHealth', doses: ['۱۰ میلی‌گرم', '۲۰ میلی‌گرم', '۴۰ میلی‌گرم'] },
  { id: 'paroxetine', fa: 'پاروکستین', en: 'Paroxetine', category: 'mentalHealth', doses: ['۱۰ میلی‌گرم', '۲۰ میلی‌گرم', '۳۰ میلی‌گرم', '۴۰ میلی‌گرم'] },
  { id: 'amitriptyline', fa: 'آمی‌تریپتیلین', en: 'Amitriptyline', category: 'mentalHealth', doses: ['۱۰ میلی‌گرم', '۲۵ میلی‌گرم', '۵۰ میلی‌گرم', '۷۵ میلی‌گرم'] },
  { id: 'trazodone', fa: 'ترازودون', en: 'Trazodone', category: 'mentalHealth', doses: ['۵۰ میلی‌گرم', '۱۰۰ میلی‌گرم', '۱۵۰ میلی‌گرم'] },
  { id: 'olanzapine', fa: 'اولانزاپین', en: 'Olanzapine', category: 'mentalHealth', doses: ['۲٫۵ میلی‌گرم', '۵ میلی‌گرم', '۱۰ میلی‌گرم', '۱۵ میلی‌گرم', '۲۰ میلی‌گرم'] },
  { id: 'aripiprazole', fa: 'آریپیپرازول', en: 'Aripiprazole', category: 'mentalHealth', doses: ['۲ میلی‌گرم', '۵ میلی‌گرم', '۱۰ میلی‌گرم', '۱۵ میلی‌گرم', '۳۰ میلی‌گرم'] },
  { id: 'lithium', fa: 'لیتیوم', en: 'Lithium carbonate', category: 'mentalHealth', doses: ['۱۵۰ میلی‌گرم', '۳۰۰ میلی‌گرم', '۴۵۰ میلی‌گرم'] },
  { id: 'buspirone', fa: 'بوسپیرون', en: 'Buspirone', category: 'mentalHealth', doses: ['۵ میلی‌گرم', '۱۰ میلی‌گرم', '۱۵ میلی‌گرم', '۳۰ میلی‌گرم'] },
  { id: 'lorazepam', fa: 'لورازپام', en: 'Lorazepam', category: 'mentalHealth', doses: ['۰٫۵ میلی‌گرم', '۱ میلی‌گرم', '۲ میلی‌گرم'] },
  { id: 'clonazepam', fa: 'کلونازپام', en: 'Clonazepam', category: 'mentalHealth', doses: ['۰٫۵ میلی‌گرم', '۱ میلی‌گرم', '۲ میلی‌گرم'] },
  { id: 'oxcarbazepine', fa: 'اکس‌کاربازپین', en: 'Oxcarbazepine', category: 'neurology', doses: ['۱۵۰ میلی‌گرم', '۳۰۰ میلی‌گرم', '۶۰۰ میلی‌گرم'] },
  { id: 'phenytoin', fa: 'فنی‌توئین', en: 'Phenytoin', category: 'neurology', doses: ['۳۰ میلی‌گرم', '۵۰ میلی‌گرم', '۱۰۰ میلی‌گرم'] },
  { id: 'pramipexole', fa: 'پرامی‌پکسول', en: 'Pramipexole', category: 'neurology', doses: ['۰٫۱۲۵ میلی‌گرم', '۰٫۲۵ میلی‌گرم', '۰٫۵ میلی‌گرم', '۱ میلی‌گرم'] },
  { id: 'ropinirole', fa: 'روپینیرول', en: 'Ropinirole', category: 'neurology', doses: ['۰٫۲۵ میلی‌گرم', '۰٫۵ میلی‌گرم', '۱ میلی‌گرم', '۲ میلی‌گرم', '۵ میلی‌گرم'] },
  { id: 'memantine', fa: 'ممانتین', en: 'Memantine', category: 'neurology', doses: ['۵ میلی‌گرم', '۱۰ میلی‌گرم', '۲۰ میلی‌گرم'] },
  { id: 'sumatriptan', fa: 'سوماتریپتان', en: 'Sumatriptan', category: 'neurology', doses: ['۲۵ میلی‌گرم', '۵۰ میلی‌گرم', '۱۰۰ میلی‌گرم', '۶ میلی‌گرم تزریقی'] },
  { id: 'rizatriptan', fa: 'ریزاتریپتان', en: 'Rizatriptan', category: 'neurology', doses: ['۵ میلی‌گرم', '۱۰ میلی‌گرم'] },
  { id: 'meloxicam', fa: 'ملوکسیکام', en: 'Meloxicam', category: 'pain', doses: ['۷٫۵ میلی‌گرم', '۱۵ میلی‌گرم'] },
  { id: 'etoricoxib', fa: 'اتوریکوکسیب', en: 'Etoricoxib', category: 'pain', doses: ['۳۰ میلی‌گرم', '۶۰ میلی‌گرم', '۹۰ میلی‌گرم', '۱۲۰ میلی‌گرم'] },
  { id: 'tizanidine', fa: 'تیزانیدین', en: 'Tizanidine', category: 'pain', doses: ['۲ میلی‌گرم', '۴ میلی‌گرم', '۶ میلی‌گرم'] },
  { id: 'morphine', fa: 'مورفین', en: 'Morphine', category: 'pain', doses: ['۵ میلی‌گرم', '۱۰ میلی‌گرم', '۱۵ میلی‌گرم', '۳۰ میلی‌گرم'] },
  { id: 'oxycodone', fa: 'اکسی‌کودون', en: 'Oxycodone', category: 'pain', doses: ['۵ میلی‌گرم', '۱۰ میلی‌گرم', '۲۰ میلی‌گرم', '۴۰ میلی‌گرم'] },
  { id: 'amoxicillin-clavulanate', fa: 'آموکسی‌سیلین / کلاوولانات', en: 'Amoxicillin / clavulanate', aliases: ['Augmentin', 'آگمنتین'], category: 'antibiotic', doses: ['۳۷۵ میلی‌گرم', '۶۲۵ میلی‌گرم', '۸۷۵/۱۲۵ میلی‌گرم'] },
  { id: 'clarithromycin', fa: 'کلاریترومایسین', en: 'Clarithromycin', category: 'antibiotic', doses: ['۲۵۰ میلی‌گرم', '۵۰۰ میلی‌گرم'] },
  { id: 'clindamycin', fa: 'کلیندامایسین', en: 'Clindamycin', category: 'antibiotic', doses: ['۱۵۰ میلی‌گرم', '۳۰۰ میلی‌گرم'] },
  { id: 'nitrofurantoin', fa: 'نیتروفورانتوئین', en: 'Nitrofurantoin', category: 'antibiotic', doses: ['۵۰ میلی‌گرم', '۱۰۰ میلی‌گرم'] },
  { id: 'trimethoprim-sulfamethoxazole', fa: 'کوتریموکسازول', en: 'Trimethoprim / sulfamethoxazole', aliases: ['Co-trimoxazole'], category: 'antibiotic', doses: ['۴۰۰/۸۰ میلی‌گرم', '۸۰۰/۱۶۰ میلی‌گرم'] },
  { id: 'cefixime', fa: 'سفیکسیم', en: 'Cefixime', category: 'antibiotic', doses: ['۲۰۰ میلی‌گرم', '۴۰۰ میلی‌گرم'] },
  { id: 'levofloxacin', fa: 'لووفلوکساسین', en: 'Levofloxacin', category: 'antibiotic', doses: ['۲۵۰ میلی‌گرم', '۵۰۰ میلی‌گرم', '۷۵۰ میلی‌گرم'] },
  { id: 'fluconazole', fa: 'فلوکونازول', en: 'Fluconazole', category: 'other', doses: ['۵۰ میلی‌گرم', '۱۰۰ میلی‌گرم', '۱۵۰ میلی‌گرم', '۲۰۰ میلی‌گرم'] },
  { id: 'acyclovir', fa: 'آسیکلوویر', en: 'Acyclovir', category: 'other', doses: ['۲۰۰ میلی‌گرم', '۴۰۰ میلی‌گرم', '۸۰۰ میلی‌گرم'] },
  { id: 'valacyclovir', fa: 'والاسیکلوویر', en: 'Valacyclovir', category: 'other', doses: ['۵۰۰ میلی‌گرم', '۱۰۰۰ میلی‌گرم'] },
  { id: 'allopurinol', fa: 'آلوپورینول', en: 'Allopurinol', category: 'rheumatology', doses: ['۱۰۰ میلی‌گرم', '۳۰۰ میلی‌گرم'] },
  { id: 'colchicine', fa: 'کلشی‌سین', en: 'Colchicine', category: 'rheumatology', doses: ['۰٫۵ میلی‌گرم', '۰٫۶ میلی‌گرم'] },
  { id: 'sulfasalazine', fa: 'سولفاسالازین', en: 'Sulfasalazine', category: 'rheumatology', doses: ['۵۰۰ میلی‌گرم'] },
  { id: 'leflunomide', fa: 'لفلونوماید', en: 'Leflunomide', category: 'rheumatology', doses: ['۱۰ میلی‌گرم', '۲۰ میلی‌گرم'] },
  { id: 'risedronate', fa: 'ریزدرونات', en: 'Risedronate', category: 'rheumatology', doses: ['۵ میلی‌گرم', '۳۵ میلی‌گرم', '۱۵۰ میلی‌گرم'] },
  { id: 'desloratadine', fa: 'دسلوراتادین', en: 'Desloratadine', category: 'respiratory', doses: ['۵ میلی‌گرم'] },
  { id: 'levocetirizine', fa: 'لووستیریزین', en: 'Levocetirizine', category: 'respiratory', doses: ['۵ میلی‌گرم'] },
  { id: 'tiotropium', fa: 'تیوتروپیوم', en: 'Tiotropium inhaler', aliases: ['Spiriva'], category: 'respiratory', doses: ['۱ پاف', '۲ پاف', '۱۸ میکروگرم'] },
  { id: 'ipratropium', fa: 'ایپراتروپیوم', en: 'Ipratropium inhaler', category: 'respiratory', doses: ['۱ پاف', '۲ پاف'] },
  { id: 'budesonide-formoterol', fa: 'بودزوناید / فورموترول', en: 'Budesonide / formoterol inhaler', aliases: ['Symbicort', 'سیمبیکورت'], category: 'respiratory', doses: ['۸۰/۴٫۵ میکروگرم', '۱۶۰/۴٫۵ میکروگرم', '۳۲۰/۹ میکروگرم'] },
  { id: 'fluticasone-salmeterol', fa: 'فلوتیکازون / سالمترول', en: 'Fluticasone / salmeterol inhaler', aliases: ['Seretide', 'Advair'], category: 'respiratory', doses: ['۵۰/۱۰۰ میکروگرم', '۵۰/۲۵۰ میکروگرم', '۵۰/۵۰۰ میکروگرم'] },
  { id: 'mirabegron', fa: 'میرابگرون', en: 'Mirabegron', category: 'urology', doses: ['۲۵ میلی‌گرم', '۵۰ میلی‌گرم'] },
  { id: 'oxybutynin', fa: 'اکسی‌بوتینین', en: 'Oxybutynin', category: 'urology', doses: ['۲٫۵ میلی‌گرم', '۵ میلی‌گرم', '۱۰ میلی‌گرم'] },
  { id: 'sildenafil', fa: 'سیلدنافیل', en: 'Sildenafil', category: 'urology', doses: ['۲۵ میلی‌گرم', '۵۰ میلی‌گرم', '۱۰۰ میلی‌گرم'] },
  { id: 'tadalafil', fa: 'تادالافیل', en: 'Tadalafil', category: 'urology', doses: ['۲٫۵ میلی‌گرم', '۵ میلی‌گرم', '۱۰ میلی‌گرم', '۲۰ میلی‌گرم'] },
  { id: 'ethinylestradiol-levonorgestrel', fa: 'اتینیل‌استرادیول / لوونورژسترل', en: 'Ethinylestradiol / levonorgestrel', category: 'womenHealth', doses: ['۲۰/۱۰۰ میکروگرم', '۳۰/۱۵۰ میکروگرم'] },
  { id: 'medroxyprogesterone', fa: 'مدروکسی‌پروژسترون', en: 'Medroxyprogesterone', category: 'womenHealth', doses: ['۲٫۵ میلی‌گرم', '۵ میلی‌گرم', '۱۰ میلی‌گرم'] },
  { id: 'clomiphene', fa: 'کلومیفن', en: 'Clomiphene', category: 'womenHealth', doses: ['۵۰ میلی‌گرم'] },
  { id: 'tretinoin-topical', fa: 'ترتینوئین موضعی', en: 'Tretinoin topical', category: 'dermatology', doses: ['۰٫۰۲۵ درصد', '۰٫۰۵ درصد', '۰٫۱ درصد'] },
  { id: 'adapalene', fa: 'آداپالن', en: 'Adapalene topical', category: 'dermatology', doses: ['۰٫۱ درصد', '۰٫۳ درصد'] },
  { id: 'clobetasol', fa: 'کلوبتازول موضعی', en: 'Clobetasol topical', category: 'dermatology', doses: ['۰٫۰۵ درصد'] },
  { id: 'ketoconazole-topical', fa: 'کتوکونازول موضعی', en: 'Ketoconazole topical', category: 'dermatology', doses: ['۲ درصد'] },
  { id: 'bimatoprost', fa: 'بیماتوپروست', en: 'Bimatoprost eye drops', category: 'ophthalmology', doses: ['۰٫۰۱ درصد', '۰٫۰۳ درصد'] },
  { id: 'dorzolamide', fa: 'دورزولامید چشمی', en: 'Dorzolamide eye drops', category: 'ophthalmology', doses: ['۲ درصد'] },
  { id: 'olopatadine-eye', fa: 'اولوپاتادین چشمی', en: 'Olopatadine eye drops', category: 'ophthalmology', doses: ['۰٫۱ درصد', '۰٫۲ درصد'] },
  { id: 'vitamin-a', fa: 'ویتامین A', en: 'Vitamin A', category: 'supplement', doses: ['۲۵۰۰ واحد', '۵۰۰۰ واحد', '۱۰۰۰۰ واحد'], guidance: GUIDANCE.labelFirst },
  { id: 'copper', fa: 'مس', en: 'Copper supplement', category: 'supplement', doses: ['۱ میلی‌گرم', '۲ میلی‌گرم'], guidance: GUIDANCE.labelFirst },
  { id: 'iodine', fa: 'ید', en: 'Iodine supplement', category: 'supplement', doses: ['۱۵۰ میکروگرم', '۲۰۰ میکروگرم'], guidance: GUIDANCE.labelFirst },
  { id: 'melatonin', fa: 'ملاتونین', en: 'Melatonin', category: 'supplement', doses: ['۱ میلی‌گرم', '۲ میلی‌گرم', '۳ میلی‌گرم', '۵ میلی‌گرم'], guidance: GUIDANCE.labelFirst },
  { id: 'ashwagandha', fa: 'آشواگاندا', en: 'Ashwagandha', category: 'natural', doses: ['۱ کپسول', '۳۰۰ میلی‌گرم', '۵۰۰ میلی‌گرم'], guidance: GUIDANCE.herbal },
  { id: 'st-johns-wort', fa: 'علف چای', en: "St. John's wort", aliases: ['گل راعی'], category: 'natural', doses: ['۱ قرص', '۳۰۰ میلی‌گرم'], guidance: GUIDANCE.herbal },
]

export function normalizeDrugSearch(value) {
  return String(value || '')
    .toLocaleLowerCase('fa')
    .replaceAll('ي', 'ی')
    .replaceAll('ك', 'ک')
    .replace(/[\u200c\s-]+/g, '')
}

export function searchMedicationCatalog(query, limit = 8) {
  const normalized = normalizeDrugSearch(query)
  if (!normalized) return []
  return MEDICATION_CATALOG
    .filter(item => normalizeDrugSearch(`${item.fa} ${item.en} ${(item.aliases || []).join(' ')}`).includes(normalized))
    .slice(0, limit)
}

export function findMedicationById(id) {
  return MEDICATION_CATALOG.find(item => item.id === id) || null
}
