export const L=(de,en,fa)=>({de,en,fa})
export const pick=(value,lang)=>value?.[lang]??value?.de??value
export const COPY={title:L('Verkalkungen in der Mammographie','Calcifications on Mammography','کلسیفیکاسیون‌ها در ماموگرافی'),subtitle:L('Kalk ist ein bildgebender Phänotyp – keine Diagnose.','Calcification is an imaging phenotype – not a diagnosis.','کلسیفیکاسیون یک فنوتیپ تصویربرداری است، نه تشخیص.'),contents:L('Lektionsinhalt','Lesson contents','محتوای درس'),flashcards:L('Flashcards','Flashcards','فلش‌کارت‌ها'),mamma:L('Mamma','Breast','پستان'),imaging:L('Bildgebung & BI-RADS','Imaging & BI-RADS','تصویربرداری و BI-RADS'),mammography:L('Mammographie','Mammography','ماموگرافی')}
export const SECTIONS=[['grundlagen','Grundlagen','Fundamentals','مبانی'],['technik','Technische Beurteilung','Technical assessment','ارزیابی فنی'],['benigne','Typisch benigne Formen','Typically benign forms','اشکال تیپیک خوش‌خیم'],['morphologie','Suspekte Morphologie','Suspicious morphology','مورفولوژی مشکوک'],['verteilung','Verteilung','Distribution','توزیع'],['kombination','Morphologie × Verteilung','Morphology × distribution','مورفولوژی × توزیع'],['kontext','Verlauf, Ausdehnung & Kontext','Evolution, extent & context','روند، وسعت و زمینه'],['modalitaeten','DCIS, Ultraschall & MRT','DCIS, ultrasound & MRI','DCIS، سونوگرافی و MRI'],['algorithmus','Algorithmus & Take Home','Algorithm & take home','الگوریتم و نکات کلیدی']].map(([id,de,en,fa],i)=>({id,label:L(de,en,fa),number:String(i+1).padStart(2,'0')}))
export const BENIGN=[
  ['Popcorn',L('Grobschollig','Coarse or popcorn-like','درشت یا پاپ‌کورنی'),L('Involutiertes Fibroadenom, Fettnekrose, dystrophe Veränderung','Involuting fibroadenoma, fat necrosis, dystrophic change','فیبروآدنوم اینولوتیو، نکروز چربی، تغییرات دیستروفیک')],
  ['Rod',L('Large rod-like','Large rod-like','میله‌ای بزرگ'),L('Grobe glatte Gang- oder Gangwandverkalkungen','Coarse smooth ductal or periductal calcifications','کلسیفیکاسیون درشت و صاف داخل یا اطراف مجرا')],
  ['Round',L('Rund / punktförmig','Round / punctate','گرد / نقطه‌ای'),L('Diffus meist benign; gruppiert nur im Gesamtkontext bewerten','Diffuse is usually benign; grouped requires context','منتشر معمولاً خوش‌خیم؛ گروهی نیازمند ارزیابی زمینه')],
  ['Rim',L('Rim calcifications','Rim calcifications','کلسیفیکاسیون حاشیه‌ای'),L('Dünn randständig, typisch bei Ölzyste oder Fettnekrose','Thin peripheral calcification, typical of oil cyst or fat necrosis','حاشیه‌ای نازک، تیپیک در کیست روغنی یا نکروز چربی')],
  ['Teacup',L('Milk of calcium','Milk of calcium','شیر کلسیم'),L('Sediment in Zysten; Teacup-Zeichen in geeigneter Projektion','Dependent cyst sediment; teacup sign on the appropriate view','رسوب وابسته در کیست؛ علامت فنجان چای در نمای مناسب')],
  ['Suture',L('Nahtverkalkungen','Suture calcifications','کلسیفیکاسیون بخیه'),L('Linear oder kurvilinear entlang postoperativen Nahtmaterials','Linear or curvilinear along postoperative suture material','خطی یا منحنی در امتداد بخیه پس از عمل')],
]
export const MORPH=[
  {key:'round',title:L('Rund','Round','گرد'),risk:L('niedrig','low','پایین'),text:L('Glatt konturiert; diffus typischerweise benign.','Smoothly marginated; diffuse distribution is typically benign.','حاشیه صاف؛ در توزیع منتشر معمولاً خوش‌خیم.')},
  {key:'amorph',title:L('Amorph','Amorphous','آمورف'),risk:L('niedrig–moderat','low–moderate','پایین–متوسط'),text:L('Sehr klein und unscharf definiert; Verteilung besonders wichtig.','Very small and indistinctly defined; distribution is especially important.','بسیار کوچک و نامشخص؛ توزیع اهمیت ویژه دارد.')},
  {key:'coarse',title:L('Grob heterogen','Coarse heterogeneous','درشت ناهمگون'),risk:L('moderat','moderate','متوسط'),text:L('Irregulär, größer als amorph, aber kleiner als grobschollig.','Irregular, larger than amorphous but smaller than coarse benign calcifications.','نامنظم، بزرگ‌تر از آمورف و کوچک‌تر از کلسیفیکاسیون درشت خوش‌خیم.')},
  {key:'pleomorphic',title:L('Fein pleomorph','Fine pleomorphic','ظریف پلئومورفیک'),risk:L('moderat–hoch','moderate–high','متوسط–بالا'),text:L('Feine Partikel unterschiedlicher Form und Größe.','Fine particles with varying shapes and sizes.','ذرات ظریف با شکل و اندازه متفاوت.')},
  {key:'linear',title:L('Fein linear / verzweigt','Fine linear / branching','ظریف خطی / شاخه‌دار'),risk:L('hoch','high','بالا'),text:L('Fein, irregulär und gangähnlich; höchste Suspektheit.','Fine, irregular and duct-like; highest suspicion.','ظریف، نامنظم و شبیه مجرا؛ بیشترین میزان شک.')},
]
export const DISTRIBUTION=[
  {key:'diffuse',title:L('Diffus','Diffuse','منتشر'),text:L('Weit über die Brust verteilt, häufig bilateral.','Widely distributed, often bilateral.','در بخش وسیعی از پستان، اغلب دوطرفه.')},
  {key:'regional',title:L('Regional','Regional','ناحیه‌ای'),text:L('Größeres Areal ohne eindeutige Orientierung an einem Gangsystem.','Larger area without clear ductal orientation.','ناحیه بزرگ‌تر بدون جهت‌گیری مشخص مجرایی.')},
  {key:'grouped',title:L('Gruppiert','Grouped','گروهی'),text:L('Konzentriert in einem begrenzten Areal; Morphologie entscheidet.','Concentrated in a limited area; morphology determines risk.','متمرکز در ناحیه محدود؛ مورفولوژی خطر را تعیین می‌کند.')},
  {key:'linear',title:L('Linear','Linear','خطی'),text:L('Entlang einer Linie, möglicherweise intraduktal.','Arranged along a line, potentially intraductal.','در امتداد یک خط، احتمالاً داخل مجرا.')},
  {key:'segmental',title:L('Segmental','Segmental','سگمنتال'),text:L('Gangsystem mit Verzweigungen; oft keilförmig zur Mamille.','A ductal system and branches, often wedge-shaped toward the nipple.','سیستم مجرایی و شاخه‌ها، اغلب گوه‌ای به‌سوی نوک پستان.')},
]
export const COMBINATIONS=[
  [L('Amorph','Amorphous','آمورف'),L('diffus / bilateral','diffuse / bilateral','منتشر / دوطرفه'),L('eher niedriges Risiko','lower risk','خطر کمتر'),'low'],
  [L('Amorph','Amorphous','آمورف'),L('gruppiert / segmental','grouped / segmental','گروهی / سگمنتال'),L('höhere Suspektheit','greater suspicion','شک بیشتر'),'mid'],
  [L('Fein pleomorph','Fine pleomorphic','ظریف پلئومورفیک'),L('gruppiert','grouped','گروهی'),L('deutlich suspekt','clearly suspicious','به‌وضوح مشکوک'),'high'],
  [L('Fein linear / verzweigt','Fine linear / branching','ظریف خطی / شاخه‌دار'),L('linear / segmental','linear / segmental','خطی / سگمنتال'),L('hochgradig suspekt','highly suspicious','بسیار مشکوک'),'high'],
]
export const CONTEXT=[
  {title:L('Verlauf','Evolution','روند'),text:L('Neu oder zunehmend? Langzeitstabilität nur anhand echter Voraufnahmen beurteilen.','New or increasing? Assess long-term stability only from actual prior studies.','جدید یا در حال افزایش؟ ثبات طولانی‌مدت فقط با تصاویر قبلی واقعی سنجیده می‌شود.')},
  {title:L('Ausdehnung','Extent','وسعت'),text:L('Gesamtausdehnung in Millimetern oder Zentimetern dokumentieren – relevant für DCIS und Therapieplanung.','Document total extent in millimetres or centimetres; relevant to DCIS and treatment planning.','وسعت کلی را به میلی‌متر یا سانتی‌متر ثبت کنید؛ برای DCIS و برنامه درمان مهم است.')},
  {title:L('Begleitbefund','Associated finding','یافته همراه'),text:L('Mass, Architekturstörung, Asymmetrie sowie Haut- oder Mamillenveränderung aktiv suchen.','Actively search for mass, architectural distortion, asymmetry, skin or nipple change.','به‌طور فعال توده، دیستورشن معماری، آسیمتری و تغییر پوست یا نوک پستان را جستجو کنید.')},
]
export const ALGORITHM=[L('Kalk erkennen','Detect calcification','شناسایی کلسیفیکاسیون'),L('Darstellung ausreichend? Gegebenenfalls Vergrößerungsaufnahme','Adequate depiction? Obtain magnification views if needed','نمایش کافی است؟ در صورت نیاز نمای بزرگنمایی'),L('Morphologie bestimmen','Determine morphology','تعیین مورفولوژی'),L('Verteilung bestimmen','Determine distribution','تعیین توزیع'),L('Verlauf + Ausdehnung + Begleitbefunde + Klinik','Evolution + extent + associated findings + clinical context','روند + وسعت + یافته‌های همراه + زمینه بالینی'),L('BI-RADS und Konsequenz','BI-RADS and management','BI-RADS و اقدام')]
export const TAKE_HOME=[L('Größe allein trennt benignen und malignen Mikrokalk nicht.','Size alone does not separate benign from malignant calcifications.','اندازه به‌تنهایی کلسیفیکاسیون خوش‌خیم و بدخیم را جدا نمی‌کند.'),L('Typisch benigne Formen sicher erkennen – suspekte Formen immer nach Morphologie und Verteilung beschreiben.','Recognise typically benign forms; always describe suspicious forms by morphology and distribution.','اشکال تیپیک خوش‌خیم را بشناسید؛ اشکال مشکوک را همیشه با مورفولوژی و توزیع توصیف کنید.'),L('Neue oder zunehmende Verkalkungen und assoziierte Mass/Distortion erhöhen die Relevanz.','New or increasing calcifications and an associated mass or distortion increase concern.','کلسیفیکاسیون جدید یا افزایشی و توده یا دیستورشن همراه اهمیت را افزایش می‌دهد.'),L('Negatives MRT oder fehlendes CEM-Enhancement hebt eine klare Biopsieindikation nicht auf.','Negative MRI or absent CEM enhancement does not cancel a clear biopsy indication.','MRI منفی یا نبود Enhancement در CEM اندیکاسیون واضح بیوپسی را لغو نمی‌کند.')]
