'use client'
import {useEffect,useMemo,useState} from 'react'
import Link from 'next/link'
import {useLanguage} from '@/providers/LanguageProvider'
import {useLessonReadStatus} from '@/hooks/useLessonReadStatus'
import {useMobileLearningLayout} from '@/hooks/useMobileLearningLayout'
import base from '@/app/abdomen/gi/divertikulitis/page.module.css'
import shared from '../grundlagen/page.module.css'
import basics from '../../mrt/basics/page.module.css'
import styles from './page.module.css'
import {ALGORITHM,BENIGN,COMBINATIONS,CONTEXT,COPY,DISTRIBUTION,L,MORPH,SECTIONS,TAKE_HOME,pick} from './content'
const ID='mammographie-mikrokalk',PATH='/mamma/bildgebung/mammographie/verkalkungen'
const READ={de:['Als gelesen markieren','Als gelesen markiert','Bitte melde dich an, um deinen Lernfortschritt zu speichern.','Anmelden'],en:['Mark as read','Marked as read','Please sign in to save your learning progress.','Sign in'],fa:['علامت‌گذاری به‌عنوان خوانده‌شده','به‌عنوان خوانده‌شده علامت‌گذاری شد','برای ذخیره پیشرفت لطفاً وارد شوید.','ورود']}
function Section({id,number,title,children}){const mobile=useMobileLearningLayout();const[open,setOpen]=useState(true);useEffect(()=>setOpen(!mobile),[mobile,id]);return <section id={id} className={`${base.section} ${basics.section} ${styles.section}`}><button type="button" className={`${base.sectionHeader} ${basics.sectionHeader}`} onClick={()=>setOpen(v=>!v)} aria-expanded={open}><span className={basics.sectionHeading}><small>{number}</small><h2>{title}</h2></span><span className={basics.sectionToggle}>{open?'−':'+'}</span></button>{open&&<div className={`${base.sectionBody} ${basics.sectionBody} ${styles.sectionBody}`}>{children}</div>}</section>}
function ReadButton({lang,isRead,toggle,authError}){const t=READ[lang]||READ.de;return <div className={base.readControl}><button type="button" className={`${base.readButton} ${basics.readButton} ${isRead?`${base.readButtonActive} ${basics.readButtonActive}`:''}`} onClick={toggle}><span className={`${base.readCheck} ${basics.readCheck}`}>{isRead?'✓':''}</span><span>{isRead?t[1]:t[0]}</span></button>{authError&&<div className={base.readError}><span>{t[2]}</span><Link href="/sign-in">{t[3]}</Link></div>}</div>}
function RiskLab({lang}){const tx=v=>pick(v,lang);const[morph,setMorph]=useState('amorph');const[dist,setDist]=useState('grouped');const mi=MORPH.findIndex(x=>x.key===morph),di=DISTRIBUTION.findIndex(x=>x.key===dist);const score=mi+(di>=3?2:di===2?1:0);const result=score>=5?L('hoch suspekt','highly suspicious','بسیار مشکوک'):score>=3?L('suspekt','suspicious','مشکوک'):L('eher niedrige Suspektheit','lower suspicion','شک کمتر');return <div className={styles.riskLab}><header><small>{tx(L('Interaktiv kombinieren','Combine interactively','ترکیب تعاملی'))}</small><strong>{tx(result)}</strong></header><div><label>{tx(L('Morphologie','Morphology','مورفولوژی'))}<select value={morph} onChange={e=>setMorph(e.target.value)}>{MORPH.map(x=><option key={x.key} value={x.key}>{tx(x.title)}</option>)}</select></label><span>×</span><label>{tx(L('Verteilung','Distribution','توزیع'))}<select value={dist} onChange={e=>setDist(e.target.value)}>{DISTRIBUTION.map(x=><option key={x.key} value={x.key}>{tx(x.title)}</option>)}</select></label></div><p>{tx(L('Die Kombination strukturiert die Risikoeinschätzung; BI-RADS und Management bleiben eine ärztliche Gesamtentscheidung.','The combination structures risk assessment; BI-RADS and management remain an integrated clinical decision.','این ترکیب ارزیابی خطر را ساختار می‌دهد؛ BI-RADS و اقدام همچنان تصمیم جامع پزشکی هستند.'))}</p></div>}
export default function Page(){const{lang}=useLanguage(),tx=v=>pick(v,lang),[active,setActive]=useState(SECTIONS[0].id),{isRead,toggleRead,authError}=useLessonReadStatus(ID),ids=useMemo(()=>SECTIONS.map(x=>x.id),[]),withLang=href=>lang==='de'?href:`${href}${href.includes('?')?'&':'?'}lang=${lang}`;useEffect(()=>{const os=ids.map(id=>{const el=document.getElementById(id);if(!el)return null;const o=new IntersectionObserver(([e])=>e.isIntersecting&&setActive(id),{rootMargin:'-18% 0px -72%',threshold:.01});o.observe(el);return o});return()=>os.forEach(o=>o?.disconnect())},[ids]);return <main className={`${base.page} ${basics.page} ${shared.page} ${styles.page} ${lang==='fa'?styles.rtl:''}`} dir={lang==='fa'?'rtl':'ltr'} lang={lang}><header className={base.header}><nav className={`${base.breadcrumb} ${basics.breadcrumb}`} aria-label={tx(COPY.contents)}><Link href={withLang('/')}>RadYar</Link><span>›</span><Link href={withLang('/lernen/mamma')}>{tx(COPY.mamma)}</Link><span>›</span><span>{tx(COPY.imaging)}</span><span>›</span><span>{tx(COPY.mammography)}</span><span>›</span><strong>{tx(COPY.title)}</strong></nav><div className={base.hero}><div className={`${base.heroText} ${basics.heroText} ${shared.heroText} ${styles.heroText}`}><h1>{tx(COPY.title)}</h1><p>{tx(COPY.subtitle)}</p><div className={base.actions}><Link className={`${base.actionBtn} ${basics.actionBtn}`} href={withLang(`/ueben/quiz?fach=mamma&n=10&themen=${ID}&from=${encodeURIComponent(withLang(PATH))}`)}>🎯 MCQ</Link><Link className={`${base.actionBtn} ${basics.actionBtn}`} href={withLang(`/flashcards/${ID}?from=${encodeURIComponent(withLang(PATH))}`)}>🧠 {tx(COPY.flashcards)}</Link></div></div><div className={`${base.heroStats} ${styles.heroStats}`}><div className={`${base.heroStat} ${basics.heroStat}`}><strong>{tx(L('Morphologie','Morphology','مورفولوژی'))}</strong><span>{tx(L('Form der Partikel','Particle form','شکل ذرات'))}</span></div><div className={`${base.heroStat} ${basics.heroStat}`}><strong>{tx(L('Verteilung','Distribution','توزیع'))}</strong><span>{tx(L('räumliches Muster','spatial pattern','الگوی فضایی'))}</span></div><div className={`${base.heroStat} ${basics.heroStat}`}><strong>{tx(L('Kontext','Context','زمینه'))}</strong><span>{tx(L('Verlauf & Ausdehnung','Evolution & extent','روند و وسعت'))}</span></div></div></div></header><div className={base.readBar}><ReadButton lang={lang} isRead={isRead} toggle={toggleRead} authError={authError}/></div><div className={base.layout}><aside className={`${base.sidebar} ${basics.sidebar}`}><div className={base.sideTitle}>{tx(COPY.contents)}</div>{SECTIONS.map(x=><button key={x.id} type="button" className={`${base.sideItem} ${basics.sideItem} ${active===x.id?`${base.sideItemActive} ${basics.sideItemActive}`:''}`} onClick={()=>document.getElementById(x.id)?.scrollIntoView({behavior:'smooth'})}><span className={basics.sideNumber}>{x.number}</span><strong>{tx(x.label)}</strong></button>)}</aside><div className={base.main}>
<Section {...SECTIONS[0]} title={tx(SECTIONS[0].label)}><p className={styles.lead}>{tx(L('Mammographische Verkalkungen sind häufig und überwiegend benign. Entscheidend sind Erscheinungsbild, räumliche Anordnung und klinisch-radiologischer Kontext.','Mammographic calcifications are common and predominantly benign. Appearance, spatial arrangement and clinical-radiologic context are decisive.','کلسیفیکاسیون ماموگرافیک شایع و عمدتاً خوش‌خیم است. ظاهر، آرایش فضایی و زمینه بالینی–رادیولوژیک تعیین‌کننده‌اند.'))}</p><div className={styles.equation}><strong>{tx(L('Morphologie','Morphology','مورفولوژی'))}</strong><span>×</span><strong>{tx(L('Verteilung','Distribution','توزیع'))}</strong><span>+</span><strong>{tx(L('Verlauf · Ausdehnung · Kontext','Evolution · extent · context','روند · وسعت · زمینه'))}</strong></div><div className={styles.rule}><strong>{tx(L('Merke','Remember','نکته'))}</strong><p>{tx(L('Die Größe allein unterscheidet Mikroverkalkungen nicht sicher in benign und maligne.','Size alone does not reliably distinguish benign from malignant calcifications.','اندازه به‌تنهایی کلسیفیکاسیون خوش‌خیم را از بدخیم جدا نمی‌کند.'))}</p></div></Section>
<Section {...SECTIONS[1]} title={tx(SECTIONS[1].label)}><div className={styles.techSplit}><article><small>2D / MAG</small><h3>{tx(L('Detailauflösung','Detail resolution','تفکیک جزئیات'))}</h3><p>{tx(L('Gezielte Vergrößerungsaufnahmen verbessern die Beurteilung von Form, Anzahl und Ausdehnung und schaffen eine Vergleichsbasis.','Targeted magnification views improve assessment of shape, number and extent and provide a comparison baseline.','نماهای بزرگنمایی هدفمند ارزیابی شکل، تعداد و وسعت را بهتر کرده و پایه مقایسه می‌سازند.'))}</p></article><article><small>DBT</small><h3>{tx(L('Räumlicher Kontext','Spatial context','زمینه فضایی'))}</h3><p>{tx(L('DBT-Schichten bestätigen und lokalisieren Kalk; die hochauflösende Detailanalyse erfolgt bei Bedarf in 2D-Vergrößerung.','DBT slices confirm and localise calcifications; high-resolution analysis uses 2D magnification when needed.','برش‌های DBT کلسیفیکاسیون را تأیید و مکان‌یابی می‌کنند؛ تحلیل با وضوح بالا در صورت نیاز با بزرگنمایی دوبعدی انجام می‌شود.'))}</p></article></div><div className={styles.caution}>{tx(L('Synthetische Rekonstruktion und Artefakte können Verkalkungen verändern oder imitieren – immer in den Quellbildern bestätigen.','Synthetic reconstruction and artefacts may alter or mimic calcifications; always confirm in source images.','بازسازی مصنوعی و آرتیفکت می‌توانند کلسیفیکاسیون را تغییر دهند یا تقلید کنند؛ همیشه در تصاویر منبع تأیید کنید.'))}</div></Section>
<Section {...SECTIONS[2]} title={tx(SECTIONS[2].label)}><div className={styles.benignList}>{BENIGN.map(([code,title,text])=><article key={code}><span>{code}</span><div><h3>{tx(title)}</h3><p>{tx(text)}</p></div></article>)}</div></Section>
<Section {...SECTIONS[3]} title={tx(SECTIONS[3].label)}><div className={styles.riskArrow}>{tx(L('steigende Suspektheit','increasing suspicion','افزایش میزان شک'))} →</div><div className={styles.morphRail}>{MORPH.map((x,i)=><article key={x.key}><span>{String(i+1).padStart(2,'0')}</span><h3>{tx(x.title)}</h3><small>{tx(x.risk)}</small><p>{tx(x.text)}</p></article>)}</div></Section>
<Section {...SECTIONS[4]} title={tx(SECTIONS[4].label)}><div className={styles.distribution}>{DISTRIBUTION.map((x,i)=><article key={x.key}><span>{String(i+1).padStart(2,'0')}</span><strong>{tx(x.title)}</strong><p>{tx(x.text)}</p></article>)}</div><div className={styles.rule}><strong>{tx(L('Duktales Muster','Ductal pattern','الگوی داکتال'))}</strong><p>{tx(L('Linear und segmental sind besonders relevant, weil sie einem Gangsystem folgen können.','Linear and segmental patterns matter because they may follow a ductal system.','الگوهای خطی و سگمنتال مهم‌اند، زیرا ممکن است مسیر سیستم مجرایی را دنبال کنند.'))}</p></div></Section>
<Section {...SECTIONS[5]} title={tx(SECTIONS[5].label)}><div className={styles.comboRows}>{COMBINATIONS.map(([a,b,c,tone],i)=><article className={styles[tone]} key={i}><strong>{tx(a)}</strong><span>+</span><strong>{tx(b)}</strong><span>→</span><b>{tx(c)}</b></article>)}</div><RiskLab lang={lang}/></Section>
<Section {...SECTIONS[6]} title={tx(SECTIONS[6].label)}><div className={styles.context}>{CONTEXT.map((x,i)=><article key={i}><span>0{i+1}</span><h3>{tx(x.title)}</h3><p>{tx(x.text)}</p></article>)}</div><div className={styles.caution}>{tx(L('Eine assoziierte Mass oder Architekturstörung kann auf eine invasive Komponente hinweisen.','An associated mass or architectural distortion may indicate an invasive component.','توده یا دیستورشن معماری همراه می‌تواند نشان‌دهنده جزء مهاجم باشد.'))}</div></Section>
<Section {...SECTIONS[7]} title={tx(SECTIONS[7].label)}><div className={styles.modalityRows}><article><strong>DCIS</strong><p>{tx(L('Suspekter Mikrokalk spricht häufig für einen duktalen Prozess, beweist aber weder reines DCIS noch eine bestimmte Histologie.','Suspicious calcifications often indicate a ductal process but prove neither pure DCIS nor a specific histology.','کلسیفیکاسیون مشکوک اغلب نشان‌دهنده فرایند داکتال است، اما DCIS خالص یا بافت‌شناسی خاصی را اثبات نمی‌کند.'))}</p></article><article><strong>{tx(L('Ultraschall','Ultrasound','سونوگرافی'))}</strong><p>{tx(L('Ein Korrelat innerhalb einer Mass, Non-Mass-Läsion oder eines Ganges kann den Biopsiezugang erleichtern; fehlendes Korrelat entwarnt nicht.','A correlate within a mass, non-mass lesion or duct may facilitate biopsy; its absence is not reassuring.','همبستگی در توده، ضایعه غیرتوده‌ای یا مجرا می‌تواند بیوپسی را آسان کند؛ نبود آن اطمینان‌بخش نیست.'))}</p></article><article><strong>MRT / CEM</strong><p>{tx(L('Kann Ausdehnung oder invasive Komponenten ergänzend zeigen, ersetzt aber bei suspektem Kalk weder Mammographie noch indizierte Histologie.','May add information on extent or invasion but does not replace mammography or indicated tissue diagnosis.','می‌تواند اطلاعاتی درباره وسعت یا تهاجم بیفزاید، اما جایگزین ماموگرافی یا تشخیص بافتی لازم نیست.'))}</p></article></div></Section>
<Section {...SECTIONS[8]} title={tx(SECTIONS[8].label)}><ol className={styles.algorithm}>{ALGORITHM.map((x,i)=><li key={i}><span>{i+1}</span><strong>{tx(x)}</strong></li>)}</ol><h3 className={styles.takeTitle}>Take Home</h3><ol className={styles.takeHome}>{TAKE_HOME.map((x,i)=><li key={i}><span>{String(i+1).padStart(2,'0')}</span><strong>{tx(x)}</strong></li>)}</ol><div className={styles.finalFormula}>{tx(L('Morphologie × Verteilung + Verlauf + Ausdehnung + Kontext → BI-RADS → Konsequenz','Morphology × distribution + evolution + extent + context → BI-RADS → management','مورفولوژی × توزیع + روند + وسعت + زمینه ← BI-RADS ← اقدام'))}</div></Section>
</div></div></main>}
