export const SECTIONS = [
  { id: 'indikationen', label: 'Indikationen', icon: '01' },
  { id: 'sequenzen', label: 'Sequenzen', icon: '02' },
  { id: 'systematik', label: 'Systematisch lesen', icon: '03' },
  { id: 'fgt-bpe', label: 'FGT & BPE', icon: '04' },
  { id: 'enhancement', label: 'Enhancement-Typen', icon: '05' },
  { id: 'prinzip', label: 'Take-Home Message', icon: '06' },
]

export const INDICATIONS = [
  { tag: 'Screening', title: 'Hochrisiko-Screening', text: 'Die kontrastmittelgestützte Mamma-MRT ist besonders wichtig bei Frauen mit deutlich erhöhtem Lebenszeitrisiko für ein Mammakarzinom.' },
  { tag: 'Staging', title: 'Präoperatives Staging', text: 'Bei histologisch gesichertem Mammakarzinom kann die MRT helfen, die tatsächliche Tumorausdehnung besser einzuschätzen.' },
  { tag: 'Response', title: 'Neoadjuvante Therapie', text: 'Die MRT dient zur Verlaufskontrolle des Tumoransprechens und zur Einschätzung eines möglichen Residualtumors.' },
  { tag: 'Suche', title: 'Okkultes Mammakarzinom', text: 'Bei axillärer Lymphknotenmetastase, aber fehlendem Primärtumornachweis in Mammographie und Sonographie, kann die MRT nach dem okkulten Primärtumor suchen.' },
  { tag: 'Klärung', title: 'Problem Solving', text: 'Ausgewählte, trotz vollständiger konventioneller Diagnostik unklar gebliebene Befunde können weiter abgeklärt werden.' },
  { tag: 'Implantat', title: 'Implantatdiagnostik', text: 'Silikon-sensitive Sequenzen beurteilen die Implantatintegrität. Für die reine Rupturdiagnostik ist kein intravenöses Gadolinium erforderlich.' },
]

export const SEQUENCES = [
  { key: 'T2', role: 'T2', accent: 'blue', intro: 'Hier schauen wir vor allem auf:', points: ['Zysten und Flüssigkeit', 'Ödem', 'Hautverdickung', 'Lymphknoten', 'T2-Signal einer Läsion'], followUp: 'T2 hilft uns vor allem dabei, eine Läsion besser zu charakterisieren.' },
  { key: 'T1', role: 'T1 vor Kontrastmittel', accent: 'violet', intro: 'Diese Sequenz ist unsere Ausgangsbasis. Sie hilft unter anderem bei der Erkennung von:', points: ['Fett', 'Blutprodukten', 'bereits vorher hohem T1-Signal'], note: 'Außerdem brauchen wir sie für die spätere Subtraktion.' },
  { key: 'T1+', role: 'T1 nach Kontrastmittel', accent: 'rose', intro: 'Nach Gadolinium werden mehrere Serien aufgenommen. Hier schauen wir:', points: ['Wo nimmt etwas Kontrastmittel auf?', 'Wie sieht das Enhancement aus?', 'Wie schnell kommt es?', 'Bleibt es bestehen oder nimmt es wieder ab?'] },
  { key: 'SUB', role: 'Subtraktion', accent: 'amber', intro: 'Dabei wird vereinfacht das Bild vor Kontrastmittel vom Bild nach Kontrastmittel abgezogen. Dadurch sieht man Enhancement deutlich besser. Sehr hilfreich bei:', points: ['kleinen Läsionen', 'Non-Mass Enhancement', 'unübersichtlichem Drüsengewebe'] },
  { key: 'MIP', role: 'Maximum Intensity Projection', accent: 'cyan', intro: 'Die MIP gibt uns einen schnellen Überblick über beide Brüste. Hier sieht man oft sofort:', points: ['Verteilung des Drüsengewebes und BPE', 'Symmetrie und Seitenunterschiede', 'auffällige Enhancements', 'Anzahl potenzieller Läsionen'] },
  { key: 'DWI', role: 'DWI / ADC', accent: 'green', intro: 'Viele maligne Tumoren zeigen eine eingeschränkte Diffusion. Typisch ist:', points: ['hohes Signal in DWI', 'niedriger ADC'], note: 'DWI ist immer nur ein zusätzlicher Baustein.' },
]

export const WORKFLOW = [
  { title: 'Indikation und Voruntersuchungen klären', text: 'Warum wurde die MRT durchgeführt: Screening, Staging, Therapiekontrolle oder Implantatdiagnostik?', detail: 'Mammographie, Sonographie, alte MRT und Biopsieergebnisse öffnen und vergleichen.' },
  { title: 'Technik prüfen', text: 'Bewegung, Fettsättigung und korrekte Kontrastmittelgabe beurteilen.' },
  { title: 'MIP ansehen', text: 'Beide Brüste im schnellen Gesamtüberblick vergleichen.' },
  { title: 'FGT und BPE beurteilen', text: 'Wie viel fibroglanduläres Gewebe ist vorhanden und wie stark enhancet das normale Drüsengewebe?' },
  { title: 'Auffällige Enhancements suchen', text: 'Nun systematisch beide Brüste durchsuchen. Jedes auffällige Enhancement zunächst einer der drei Grundkategorien zuordnen,', inlineEmphasis: 'erst danach erfolgt die weitere Charakterisierung.', categories: [
    { title: 'Focus', text: 'Sehr kleiner Punkt, dessen Form nicht sicher beurteilbar ist.' },
    { title: 'Mass', text: 'Dreidimensionale raumfordernde Läsion.' },
    { title: 'Non-Mass Enhancement', text: 'Enhancement ohne klare dreidimensionale Raumforderung.' },
  ] },
  { title: 'Sequenzen abgleichen', text: 'Suspekte Läsionen in allen Sequenzen korrelieren.' },
  { title: 'Umgebung prüfen', text: 'Haut, Mamille, Pectoralis, Thoraxwand und Lymphknoten nicht vergessen.' },
]

export const FGT_CATEGORIES = [
  { key: 'a', title: 'Almost entirely fat', text: 'Fast vollständig fettige Brust mit nur sehr wenig fibroglandulärem Gewebe.' },
  { key: 'b', title: 'Scattered fibroglandular tissue', text: 'Vereinzelte Bereiche fibroglandulären Gewebes.' },
  { key: 'c', title: 'Heterogeneous fibroglandular tissue', text: 'Deutlich vorhandenes, heterogen verteiltes fibroglanduläres Gewebe.' },
  { key: 'd', title: 'Extreme fibroglandular tissue', text: 'Sehr große Menge fibroglandulären Gewebes.' },
]

export const BPE_CATEGORIES = [
  { key: '01', title: 'Minimal', text: 'Kaum Enhancement des normalen Brustparenchyms.' },
  { key: '02', title: 'Mild', text: 'Geringes Enhancement.' },
  { key: '03', title: 'Moderate', text: 'Deutlich sichtbares Enhancement größerer Anteile des Drüsengewebes.' },
  { key: '04', title: 'Marked', text: 'Ausgeprägtes Enhancement des normalen Brustparenchyms.' },
]

const EN = {
  'Indikationen':'Indications','Sequenzen':'Sequences','Systematisch lesen':'Systematic reading','Enhancement-Typen':'Enhancement types','Das wichtigste Prinzip':'The key principle','Take-Home Message':'Take-home message',
  'Höchste Sensitivität':'Highest sensitivity','Tumorvaskularisation und Kontrastmittelaufnahme sichtbar machen.':'Visualise tumour vascularity and contrast enhancement.','Multiparametrisch':'Multiparametric','Jede Sequenz beantwortet eine andere diagnostische Frage.':'Each sequence answers a different diagnostic question.','Erst klassifizieren':'Classify first','Dann Morphologie, Diffusion und Kinetik bewerten.':'Then assess morphology, diffusion and kinetics.',
  'Mamma':'Breast','Bildgebung':'Imaging','Mamma-MRT':'Breast MRI','Basics':'Basics','Inhaltsverzeichnis':'Contents',
  'Indikationen, Sequenzen und ein systematischer Einstieg in die Befundung.':'Indications, sequences and a systematic approach to interpretation.','Lernziele':'Learning objectives','Nach dieser Lektion kannst du':'After this lesson you can',
  'Indikationen gezielt einordnen':'select appropriate indications','das MRT-Protokoll sicher lesen':'read the MRI protocol confidently','FGT, BPE, Focus, Mass und NME unterscheiden':'distinguish FGT, BPE, focus, mass and NME','Flashcards':'Flashcards',
  '01 · Wann einsetzen?':'01 · When to use it','02 · Protokoll':'02 · Protocol','03 · Workflow':'03 · Workflow','04 · Nicht verwechseln':'04 · Do not confuse','05 · BI-RADS-Logik':'05 · BI-RADS logic','06 · Take home':'06 · Take home',
  'Wann einsetzen?':'When to use it','Welche Sequenzen brauchen wir?':'Which sequences do we need?','Wie liest man eine Mamma-MRT systematisch?':'How do you read a breast MRI systematically?','FGT und BPE':'FGT and BPE','Die drei wichtigsten Enhancement-Typen':'The three key enhancement types',
  'Die Mamma-MRT ist die':'Breast MRI is the','sensitivste bildgebende Methode':'most sensitive imaging method','zum Nachweis eines Mammakarzinoms. Ihre hohe Sensitivität beruht vor allem auf der Darstellung der':'for detecting breast cancer. Its high sensitivity is mainly based on visualising','Tumorvaskularisation und Kontrastmittelaufnahme':'tumour vascularity and contrast enhancement','Gleichzeitig ist die Spezifität begrenzt: Auch zahlreiche benigne Veränderungen können Kontrastmittel aufnehmen.':'At the same time, specificity is limited: many benign changes can also enhance.',
  'Screening':'Screening','Hochrisiko-Screening':'High-risk screening','Die kontrastmittelgestützte Mamma-MRT ist besonders wichtig bei Frauen mit deutlich erhöhtem Lebenszeitrisiko für ein Mammakarzinom.':'Contrast-enhanced breast MRI is particularly important in women with a markedly increased lifetime risk of breast cancer.',
  'Staging':'Staging','Präoperatives Staging':'Preoperative staging','Bei histologisch gesichertem Mammakarzinom kann die MRT helfen, die tatsächliche Tumorausdehnung besser einzuschätzen.':'In histologically proven breast cancer, MRI can help assess the true extent of disease.',
  'Response':'Response','Neoadjuvante Therapie':'Neoadjuvant therapy','Die MRT dient zur Verlaufskontrolle des Tumoransprechens und zur Einschätzung eines möglichen Residualtumors.':'MRI is used to monitor treatment response and assess possible residual tumour.',
  'Suche':'Search','Okkultes Mammakarzinom':'Occult breast cancer','Bei axillärer Lymphknotenmetastase, aber fehlendem Primärtumornachweis in Mammographie und Sonographie, kann die MRT nach dem okkulten Primärtumor suchen.':'With an axillary nodal metastasis but no primary found on mammography or ultrasound, MRI may identify an occult primary tumour.',
  'Klärung':'Clarification','Problem Solving':'Problem solving','Ausgewählte, trotz vollständiger konventioneller Diagnostik unklar gebliebene Befunde können weiter abgeklärt werden.':'Selected findings that remain unclear after complete conventional imaging can be investigated further.',
  'Implantat':'Implant','Implantatdiagnostik':'Implant assessment','Silikon-sensitive Sequenzen beurteilen die Implantatintegrität. Für die reine Rupturdiagnostik ist kein intravenöses Gadolinium erforderlich.':'Silicone-sensitive sequences assess implant integrity. Intravenous gadolinium is not required for rupture assessment alone.',
  'Problem Solving · Beispiele':'Problem solving · examples','Wenn die konventionelle Diagnostik unklar bleibt':'When conventional imaging remains inconclusive','nicht sicher erklärbare Asymmetrie':'unexplained asymmetry','unklare Architekturstörung':'indeterminate architectural distortion','diskrepante Befunde zwischen Mammographie und Sonographie':'discordant mammographic and ultrasound findings','schwer beurteilbare postoperative Veränderungen':'difficult postoperative changes','Wichtig':'Important',
  'Die MRT sollte nicht dazu verwendet werden, eine indizierte Biopsie eines suspekten Befundes zu vermeiden. Ein klar suspekter und bioptisch zugänglicher Befund sollte in der Regel histologisch abgeklärt werden.':'MRI should not be used to avoid an indicated biopsy. A clearly suspicious and biopsy-accessible finding should generally undergo histological assessment.',
  'Ein typisches Mamma-MRT-Protokoll besteht aus mehreren Sequenzen. Jede beantwortet eine andere Frage.':'A typical breast MRI protocol includes several sequences. Each answers a different question.','Hier schauen wir vor allem auf:':'We mainly assess:','Zysten und Flüssigkeit':'cysts and fluid','Ödem':'oedema','Hautverdickung':'skin thickening','Lymphknoten':'lymph nodes','T2-Signal einer Läsion':'T2 signal of a lesion','T2 hilft uns vor allem dabei, eine Läsion besser zu charakterisieren.':'T2 primarily helps characterise a lesion.',
  'T1 vor Kontrastmittel':'Pre-contrast T1','Diese Sequenz ist unsere Ausgangsbasis. Sie hilft unter anderem bei der Erkennung von:':'This sequence is our baseline. It helps identify:','Fett':'fat','Blutprodukten':'blood products','bereits vorher hohem T1-Signal':'pre-existing high T1 signal','Außerdem brauchen wir sie für die spätere Subtraktion.':'It is also required for later subtraction.',
  'T1 nach Kontrastmittel':'Post-contrast T1','Nach Gadolinium werden mehrere Serien aufgenommen. Hier schauen wir:':'Several series are acquired after gadolinium. We assess:','Wo nimmt etwas Kontrastmittel auf?':'Where is there enhancement?','Wie sieht das Enhancement aus?':'What does the enhancement look like?','Wie schnell kommt es?':'How quickly does it appear?','Bleibt es bestehen oder nimmt es wieder ab?':'Does it persist or decrease again?',
  'Subtraktion':'Subtraction','Dabei wird vereinfacht das Bild vor Kontrastmittel vom Bild nach Kontrastmittel abgezogen. Dadurch sieht man Enhancement deutlich besser. Sehr hilfreich bei:':'The pre-contrast image is subtracted from the post-contrast image, making enhancement much more conspicuous. Particularly useful for:','kleinen Läsionen':'small lesions','unübersichtlichem Drüsengewebe':'complex glandular tissue',
  'Die MIP gibt uns einen schnellen Überblick über beide Brüste. Hier sieht man oft sofort:':'The MIP provides a rapid overview of both breasts. It quickly shows:','Verteilung des Drüsengewebes und BPE':'distribution of fibroglandular tissue and BPE','Symmetrie und Seitenunterschiede':'symmetry and side-to-side differences','auffällige Enhancements':'abnormal enhancements','Anzahl potenzieller Läsionen':'number of potential lesions',
  'Viele maligne Tumoren zeigen eine eingeschränkte Diffusion. Typisch ist:':'Many malignant tumours show restricted diffusion. Typical findings are:','hohes Signal in DWI':'high signal on DWI','niedriger ADC':'low ADC','DWI ist immer nur ein zusätzlicher Baustein.':'DWI is always an adjunct.','Merke':'Remember','T1 nach Kontrastmittel ist einer der wichtigsten Teile der Mamma-MRT.':'Post-contrast T1 is one of the most important parts of breast MRI.','Ein niedriger ADC bedeutet nicht automatisch Krebs.':'A low ADC does not automatically mean cancer.','Die MIP ist perfekt zum Suchen, aber nicht zur endgültigen Beurteilung.':'The MIP is excellent for searching, but not for final assessment.',
  'Ein fester Ablauf hilft, nichts zu übersehen.':'A fixed workflow helps avoid missing findings.','Indikation und Voruntersuchungen klären':'Clarify indication and prior studies','Warum wurde die MRT durchgeführt: Screening, Staging, Therapiekontrolle oder Implantatdiagnostik?':'Why was MRI performed: screening, staging, treatment monitoring or implant assessment?','Mammographie, Sonographie, alte MRT und Biopsieergebnisse öffnen und vergleichen.':'Open and compare mammography, ultrasound, prior MRI and biopsy results.','Technik prüfen':'Check technique','Bewegung, Fettsättigung und korrekte Kontrastmittelgabe beurteilen.':'Assess motion, fat suppression and correct contrast administration.','MIP ansehen':'Review the MIP','Beide Brüste im schnellen Gesamtüberblick vergleichen.':'Compare both breasts in a rapid overview.','FGT und BPE beurteilen':'Assess FGT and BPE','Wie viel fibroglanduläres Gewebe ist vorhanden und wie stark enhancet das normale Drüsengewebe?':'How much fibroglandular tissue is present and how strongly does normal tissue enhance?','Auffällige Enhancements suchen':'Search for abnormal enhancements','Nun systematisch beide Brüste durchsuchen. Jedes auffällige Enhancement zunächst einer der drei Grundkategorien zuordnen,':'Now search both breasts systematically. First assign every abnormal enhancement to one of the three basic categories,','erst danach erfolgt die weitere Charakterisierung.':'only then proceed with further characterisation.','Sehr kleiner Punkt, dessen Form nicht sicher beurteilbar ist.':'A tiny dot whose shape cannot be assessed reliably.','Dreidimensionale raumfordernde Läsion.':'A three-dimensional space-occupying lesion.','Enhancement ohne klare dreidimensionale Raumforderung.':'Enhancement without a clear three-dimensional mass.','Sequenzen abgleichen':'Correlate sequences','Suspekte Läsionen in allen Sequenzen korrelieren.':'Correlate suspicious lesions across all sequences.','Umgebung prüfen':'Check surrounding structures','Haut, Mamille, Pectoralis, Thoraxwand und Lymphknoten nicht vergessen.':'Do not forget skin, nipple, pectoralis, chest wall and lymph nodes.',
  'Fibroglanduläres Gewebe':'Fibroglandular tissue','FGT beschreibt die':'FGT describes the','Menge des fibroglandulären Brustgewebes':'amount of fibroglandular breast tissue','– unabhängig davon, wie stark dieses nach Kontrastmittelgabe anreichert.':'— independent of how strongly it enhances after contrast.','FGT-Kategorien in voller Größe öffnen':'Open FGT categories full size','Vier MRT-Beispiele der FGT-Kategorien von fast vollständig fettig bis extrem fibroglandulär':'Four MRI examples of FGT categories from almost entirely fatty to extreme fibroglandular tissue','FGT a–d im MRT':'FGT a–d on MRI','Zum Vergrößern Bild öffnen':'Open image to enlarge','Nach BI-RADS wird das FGT qualitativ in vier Kategorien eingeteilt:':'BI-RADS qualitatively divides FGT into four categories:','Fast vollständig fettige Brust mit nur sehr wenig fibroglandulärem Gewebe.':'Almost entirely fatty breast with very little fibroglandular tissue.','Vereinzelte Bereiche fibroglandulären Gewebes.':'Scattered areas of fibroglandular tissue.','Deutlich vorhandenes, heterogen verteiltes fibroglanduläres Gewebe.':'A substantial, heterogeneously distributed amount of fibroglandular tissue.','Sehr große Menge fibroglandulären Gewebes.':'A very large amount of fibroglandular tissue.','FGT ist nicht dasselbe wie mammographische Brustdichte':'FGT is not the same as mammographic breast density','Beide beschreiben zwar die Zusammensetzung der Brust, werden jedoch mit unterschiedlichen Modalitäten beurteilt. Die MRT-Kategorie beschreibt die sichtbare Menge des fibroglandulären Gewebes in der MRT.':'Both describe breast composition, but they are assessed with different modalities. The MRI category describes the visible amount of fibroglandular tissue on MRI.',
  'Normales Parenchym':'Normal parenchyma','BPE beschreibt, wie stark das':'BPE describes how strongly','normale fibroglanduläre Brustgewebe nach Kontrastmittelgabe anreichert':'normal fibroglandular breast tissue enhances after contrast','BPE-Kategorien in voller Größe öffnen':'Open BPE categories full size','Vier MRT-Beispiele der BPE-Kategorien minimal, mild, moderate und marked':'Four MRI examples of the BPE categories minimal, mild, moderate and marked','BPE minimal–marked im MRT':'BPE minimal–marked on MRI','BI-RADS unterscheidet vier Kategorien:':'BI-RADS distinguishes four categories:','Kaum Enhancement des normalen Brustparenchyms.':'Almost no enhancement of normal breast parenchyma.','Geringes Enhancement.':'Mild enhancement.','Deutlich sichtbares Enhancement größerer Anteile des Drüsengewebes.':'Clearly visible enhancement of larger portions of glandular tissue.','Ausgeprägtes Enhancement des normalen Brustparenchyms.':'Marked enhancement of normal breast parenchyma.','Visuelle Beurteilung':'Visual assessment','Diese Einteilung erfolgt visuell. BI-RADS empfiehlt keine starre prozentuale Einteilung.':'This classification is visual. BI-RADS does not recommend rigid percentage thresholds.',
  'FGT und BPE nicht verwechseln':'Do not confuse FGT and BPE','FGT beantwortet:':'FGT answers:','Wie viel Drüsengewebe ist vorhanden?':'How much glandular tissue is present?','BPE beantwortet:':'BPE answers:','Wie stark nimmt dieses normale Drüsengewebe Kontrastmittel auf?':'How strongly does this normal glandular tissue enhance?','Daher können beispielsweise beide Konstellationen auftreten:':'Therefore, both of these combinations may occur:','viel FGT + minimales BPE':'high FGT + minimal BPE','oder':'or','wenig FGT + relativ deutliches BPE':'low FGT + relatively marked BPE','Die beiden Parameter sind miteinander verbunden, aber nicht identisch.':'The two parameters are related, but not identical.','Interpretation':'Interpretation','Warum ist BPE wichtig?':'Why is BPE important?','Starkes BPE kann kleine Läsionen schwieriger erkennbar machen und die Interpretation erschweren.':'Marked BPE can obscure small lesions and make interpretation more difficult.','BPE kann asymmetrisch oder fokal ausgeprägt sein und dadurch eine Läsion imitieren. Sein Ausmaß wird unter anderem durch hormonelle Faktoren beeinflusst.':'BPE may be asymmetric or focal and thereby mimic a lesion. Its degree is influenced by hormonal factors, among others.','Ein scheinbares Enhancement deshalb immer im Kontext des gesamten Parenchyms beurteilen.':'Always assess apparent enhancement in the context of the entire parenchyma.',
  'Zu klein für eine zuverlässige morphologische Charakterisierung.':'Too small for reliable morphological characterisation.','Eine echte dreidimensionale Läsion.':'A true three-dimensional lesion.','Form, Rand und internes Enhancement können beurteilt werden.':'Shape, margin and internal enhancement can be assessed.','Ein':'A','ist ein kontrastmittelaufnehmender Bereich, der:':'is an enhancing area that:','vom normalen BPE abgrenzbar ist,':'can be distinguished from normal BPE,','aber keine dreidimensionale Mass bildet':'but does not form a three-dimensional mass','und nicht lediglich einen kleinen Focus darstellt.':'and is not merely a small focus.','Nicht sofort fragen':'Do not ask immediately','„Ist das Krebs?“':'“Is this cancer?”','Schritt 1':'Step 1','BPE oder echter Befund?':'BPE or a true finding?','Schritt 2':'Step 2','Focus, Mass oder NME?':'Focus, mass or NME?','Schritt 3':'Step 3','Morphologie · T2 · DWI · Kinetik · Begleitbefunde':'Morphology · T2 · DWI · kinetics · associated findings',
}

const FA = {
  'Indikationen':'اندیکاسیون‌ها','Sequenzen':'سکانس‌ها','Systematisch lesen':'خواندن سیستماتیک','Enhancement-Typen':'انواع جذب کنتراست','Das wichtigste Prinzip':'اصل کلیدی','Take-Home Message':'پیام نهایی','Höchste Sensitivität':'بالاترین حساسیت','Tumorvaskularisation und Kontrastmittelaufnahme sichtbar machen.':'نمایش عروق تومور و جذب ماده حاجب.','Multiparametrisch':'چندپارامتری','Jede Sequenz beantwortet eine andere diagnostische Frage.':'هر سکانس به یک سؤال تشخیصی متفاوت پاسخ می‌دهد.','Erst klassifizieren':'ابتدا طبقه‌بندی','Dann Morphologie, Diffusion und Kinetik bewerten.':'سپس مورفولوژی، دیفیوژن و کینتیک را ارزیابی کنید.','Mamma':'پستان','Bildgebung':'تصویربرداری','Mamma-MRT':'MRI پستان','Basics':'مبانی','Inhaltsverzeichnis':'فهرست مطالب','Indikationen, Sequenzen und ein systematischer Einstieg in die Befundung.':'اندیکاسیون‌ها، سکانس‌ها و رویکردی سیستماتیک برای تفسیر.','Lernziele':'اهداف یادگیری','Nach dieser Lektion kannst du':'پس از این درس می‌توانید','Indikationen gezielt einordnen':'اندیکاسیون‌ها را درست انتخاب کنید','das MRT-Protokoll sicher lesen':'پروتکل MRI را با اطمینان بخوانید','FGT, BPE, Focus, Mass und NME unterscheiden':'FGT، BPE، Focus، Mass و NME را از هم تفکیک کنید','Flashcards':'فلش‌کارت‌ها',
  '01 · Wann einsetzen?':'۰۱ · چه زمانی استفاده کنیم؟','02 · Protokoll':'۰۲ · پروتکل','03 · Workflow':'۰۳ · روند بررسی','04 · Nicht verwechseln':'۰۴ · اشتباه نگیرید','05 · BI-RADS-Logik':'۰۵ · منطق BI-RADS','06 · Take home':'۰۶ · نکته پایانی','Welche Sequenzen brauchen wir?':'به کدام سکانس‌ها نیاز داریم؟','Wie liest man eine Mamma-MRT systematisch?':'MRI پستان را چگونه سیستماتیک بخوانیم؟','FGT und BPE':'FGT و BPE','Die drei wichtigsten Enhancement-Typen':'سه نوع مهم جذب کنتراست',
  'Die Mamma-MRT ist die':'MRI پستان','sensitivste bildgebende Methode':'حساس‌ترین روش تصویربرداری','zum Nachweis eines Mammakarzinoms. Ihre hohe Sensitivität beruht vor allem auf der Darstellung der':'برای تشخیص سرطان پستان است. حساسیت بالای آن عمدتاً به نمایش','Tumorvaskularisation und Kontrastmittelaufnahme':'عروق تومور و جذب ماده حاجب','Gleichzeitig ist die Spezifität begrenzt: Auch zahlreiche benigne Veränderungen können Kontrastmittel aufnehmen.':'مربوط می‌شود. با این حال ویژگی محدود است و بسیاری از تغییرات خوش‌خیم نیز می‌توانند کنتراست بگیرند.',
  'Screening':'غربالگری','Hochrisiko-Screening':'غربالگری پرخطر','Die kontrastmittelgestützte Mamma-MRT ist besonders wichtig bei Frauen mit deutlich erhöhtem Lebenszeitrisiko für ein Mammakarzinom.':'MRI پستان با کنتراست در زنانی که خطر مادام‌العمر سرطان پستان در آن‌ها به‌وضوح افزایش یافته اهمیت ویژه دارد.','Staging':'مرحله‌بندی','Präoperatives Staging':'مرحله‌بندی پیش از عمل','Bei histologisch gesichertem Mammakarzinom kann die MRT helfen, die tatsächliche Tumorausdehnung besser einzuschätzen.':'در سرطان پستان اثبات‌شده با بافت‌شناسی، MRI به برآورد بهتر گسترش واقعی تومور کمک می‌کند.','Response':'پاسخ درمانی','Neoadjuvante Therapie':'درمان نئوادجوانت','Die MRT dient zur Verlaufskontrolle des Tumoransprechens und zur Einschätzung eines möglichen Residualtumors.':'MRI برای پایش پاسخ تومور و ارزیابی تومور باقی‌مانده احتمالی استفاده می‌شود.','Suche':'جست‌وجو','Okkultes Mammakarzinom':'سرطان پستان مخفی','Bei axillärer Lymphknotenmetastase, aber fehlendem Primärtumornachweis in Mammographie und Sonographie, kann die MRT nach dem okkulten Primärtumor suchen.':'در متاستاز گره لنفاوی آگزیلاری بدون یافتن تومور اولیه در ماموگرافی و سونوگرافی، MRI می‌تواند تومور اولیه مخفی را جست‌وجو کند.','Klärung':'بررسی تکمیلی','Problem Solving':'حل مسئله','Ausgewählte, trotz vollständiger konventioneller Diagnostik unklar gebliebene Befunde können weiter abgeklärt werden.':'یافته‌های منتخب که پس از تصویربرداری معمول کامل همچنان نامشخص‌اند، می‌توانند بیشتر بررسی شوند.','Implantat':'ایمپلنت','Implantatdiagnostik':'ارزیابی ایمپلنت','Silikon-sensitive Sequenzen beurteilen die Implantatintegrität. Für die reine Rupturdiagnostik ist kein intravenöses Gadolinium erforderlich.':'سکانس‌های حساس به سیلیکون یکپارچگی ایمپلنت را ارزیابی می‌کنند. برای بررسی صرف پارگی، گادولینیوم وریدی لازم نیست.',
  'Problem Solving · Beispiele':'حل مسئله · نمونه‌ها','Wenn die konventionelle Diagnostik unklar bleibt':'وقتی تصویربرداری معمول پاسخ روشن نمی‌دهد','nicht sicher erklärbare Asymmetrie':'عدم تقارن بدون توضیح قطعی','unklare Architekturstörung':'دیستورشن معماری نامشخص','diskrepante Befunde zwischen Mammographie und Sonographie':'یافته‌های ناهمخوان ماموگرافی و سونوگرافی','schwer beurteilbare postoperative Veränderungen':'تغییرات پس از عمل با ارزیابی دشوار','Wichtig':'مهم','Die MRT sollte nicht dazu verwendet werden, eine indizierte Biopsie eines suspekten Befundes zu vermeiden. Ein klar suspekter und bioptisch zugänglicher Befund sollte in der Regel histologisch abgeklärt werden.':'نباید از MRI برای اجتناب از بیوپسی اندیکاسیون‌دار استفاده کرد. یافته واضحاً مشکوک و قابل بیوپسی معمولاً باید بافت‌شناسی شود.',
  'Ein typisches Mamma-MRT-Protokoll besteht aus mehreren Sequenzen. Jede beantwortet eine andere Frage.':'یک پروتکل معمول MRI پستان از چند سکانس تشکیل می‌شود و هر کدام به سؤال متفاوتی پاسخ می‌دهد.','Hier schauen wir vor allem auf:':'در اینجا عمدتاً بررسی می‌کنیم:','Zysten und Flüssigkeit':'کیست‌ها و مایع','Ödem':'ادم','Hautverdickung':'ضخیم‌شدگی پوست','Lymphknoten':'گره‌های لنفاوی','T2-Signal einer Läsion':'سیگنال T2 ضایعه','T2 hilft uns vor allem dabei, eine Läsion besser zu charakterisieren.':'T2 عمدتاً به توصیف بهتر ضایعه کمک می‌کند.','T1 vor Kontrastmittel':'T1 پیش از کنتراست','Diese Sequenz ist unsere Ausgangsbasis. Sie hilft unter anderem bei der Erkennung von:':'این سکانس خط پایه ماست و به شناسایی موارد زیر کمک می‌کند:','Fett':'چربی','Blutprodukten':'محصولات خونی','bereits vorher hohem T1-Signal':'سیگنال بالای از پیش موجود در T1','Außerdem brauchen wir sie für die spätere Subtraktion.':'همچنین برای ساب‌ترکشن بعدی لازم است.','T1 nach Kontrastmittel':'T1 پس از کنتراست','Nach Gadolinium werden mehrere Serien aufgenommen. Hier schauen wir:':'پس از گادولینیوم چند سری گرفته می‌شود. بررسی می‌کنیم:','Wo nimmt etwas Kontrastmittel auf?':'کجا جذب کنتراست وجود دارد؟','Wie sieht das Enhancement aus?':'الگوی جذب کنتراست چگونه است؟','Wie schnell kommt es?':'با چه سرعتی ظاهر می‌شود؟','Bleibt es bestehen oder nimmt es wieder ab?':'پایدار می‌ماند یا کاهش می‌یابد؟','Subtraktion':'ساب‌ترکشن','Dabei wird vereinfacht das Bild vor Kontrastmittel vom Bild nach Kontrastmittel abgezogen. Dadurch sieht man Enhancement deutlich besser. Sehr hilfreich bei:':'تصویر پیش از کنتراست از تصویر پس از کنتراست کم می‌شود و جذب کنتراست واضح‌تر دیده می‌شود. به‌ویژه مفید برای:','kleinen Läsionen':'ضایعات کوچک','unübersichtlichem Drüsengewebe':'بافت غده‌ای پیچیده','Die MIP gibt uns einen schnellen Überblick über beide Brüste. Hier sieht man oft sofort:':'MIP نمای سریعی از هر دو پستان می‌دهد و موارد زیر را سریع نشان می‌دهد:','Verteilung des Drüsengewebes und BPE':'توزیع بافت غده‌ای و BPE','Symmetrie und Seitenunterschiede':'تقارن و تفاوت دو طرف','auffällige Enhancements':'جذب‌های غیرطبیعی','Anzahl potenzieller Läsionen':'تعداد ضایعات احتمالی','Viele maligne Tumoren zeigen eine eingeschränkte Diffusion. Typisch ist:':'بسیاری از تومورهای بدخیم محدودیت دیفیوژن دارند. یافته‌های تیپیک:','hohes Signal in DWI':'سیگنال بالا در DWI','niedriger ADC':'ADC پایین','DWI ist immer nur ein zusätzlicher Baustein.':'DWI همیشه یک ابزار تکمیلی است.','Merke':'به خاطر بسپارید','T1 nach Kontrastmittel ist einer der wichtigsten Teile der Mamma-MRT.':'T1 پس از کنتراست یکی از مهم‌ترین بخش‌های MRI پستان است.','Ein niedriger ADC bedeutet nicht automatisch Krebs.':'ADC پایین خودبه‌خود به معنی سرطان نیست.','Die MIP ist perfekt zum Suchen, aber nicht zur endgültigen Beurteilung.':'MIP برای جست‌وجو عالی است، اما برای ارزیابی نهایی کافی نیست.',
  'Ein fester Ablauf hilft, nichts zu übersehen.':'روند ثابت کمک می‌کند یافته‌ای از قلم نیفتد.','Indikation und Voruntersuchungen klären':'اندیکاسیون و بررسی‌های قبلی را مشخص کنید','Warum wurde die MRT durchgeführt: Screening, Staging, Therapiekontrolle oder Implantatdiagnostik?':'MRI چرا انجام شده است: غربالگری، مرحله‌بندی، پایش درمان یا بررسی ایمپلنت؟','Mammographie, Sonographie, alte MRT und Biopsieergebnisse öffnen und vergleichen.':'ماموگرافی، سونوگرافی، MRI قبلی و نتایج بیوپسی را باز و مقایسه کنید.','Technik prüfen':'کیفیت تکنیکی را بررسی کنید','Bewegung, Fettsättigung und korrekte Kontrastmittelgabe beurteilen.':'حرکت، سرکوب چربی و تزریق صحیح کنتراست را ارزیابی کنید.','MIP ansehen':'MIP را ببینید','Beide Brüste im schnellen Gesamtüberblick vergleichen.':'هر دو پستان را در نمای کلی سریع مقایسه کنید.','FGT und BPE beurteilen':'FGT و BPE را ارزیابی کنید','Wie viel fibroglanduläres Gewebe ist vorhanden und wie stark enhancet das normale Drüsengewebe?':'چه مقدار بافت فیبروگلاندولار وجود دارد و بافت طبیعی چقدر کنتراست می‌گیرد؟','Auffällige Enhancements suchen':'جذب‌های غیرطبیعی را جست‌وجو کنید','Nun systematisch beide Brüste durchsuchen. Jedes auffällige Enhancement zunächst einer der drei Grundkategorien zuordnen,':'اکنون هر دو پستان را سیستماتیک جست‌وجو کنید. هر جذب غیرطبیعی را ابتدا در یکی از سه دسته اصلی قرار دهید،','erst danach erfolgt die weitere Charakterisierung.':'و فقط سپس توصیف بیشتر را انجام دهید.','Sehr kleiner Punkt, dessen Form nicht sicher beurteilbar ist.':'نقطه بسیار کوچک که شکل آن قابل ارزیابی مطمئن نیست.','Dreidimensionale raumfordernde Läsion.':'ضایعه فضاگیر سه‌بعدی.','Enhancement ohne klare dreidimensionale Raumforderung.':'جذب کنتراست بدون توده سه‌بعدی مشخص.','Sequenzen abgleichen':'سکانس‌ها را تطبیق دهید','Suspekte Läsionen in allen Sequenzen korrelieren.':'ضایعات مشکوک را در همه سکانس‌ها تطبیق دهید.','Umgebung prüfen':'ساختارهای اطراف را بررسی کنید','Haut, Mamille, Pectoralis, Thoraxwand und Lymphknoten nicht vergessen.':'پوست، نوک پستان، عضله پکتورال، دیواره قفسه سینه و گره‌های لنفاوی را فراموش نکنید.',
  'Fibroglanduläres Gewebe':'بافت فیبروگلاندولار','FGT beschreibt die':'FGT توصیف‌کننده','Menge des fibroglandulären Brustgewebes':'مقدار بافت فیبروگلاندولار پستان','– unabhängig davon, wie stark dieses nach Kontrastmittelgabe anreichert.':'است، مستقل از میزان جذب کنتراست.','FGT-Kategorien in voller Größe öffnen':'باز کردن تصویر کامل دسته‌های FGT','Vier MRT-Beispiele der FGT-Kategorien von fast vollständig fettig bis extrem fibroglandulär':'چهار نمونه MRI از دسته‌های FGT، از تقریباً کاملاً چرب تا بسیار فیبروگلاندولار','FGT a–d im MRT':'FGT a–d در MRI','Zum Vergrößern Bild öffnen':'برای بزرگ‌نمایی تصویر را باز کنید','Nach BI-RADS wird das FGT qualitativ in vier Kategorien eingeteilt:':'در BI-RADS، FGT به چهار دسته کیفی تقسیم می‌شود:','Fast vollständig fettige Brust mit nur sehr wenig fibroglandulärem Gewebe.':'پستان تقریباً کاملاً چرب با مقدار بسیار کم بافت فیبروگلاندولار.','Vereinzelte Bereiche fibroglandulären Gewebes.':'نواحی پراکنده بافت فیبروگلاندولار.','Deutlich vorhandenes, heterogen verteiltes fibroglanduläres Gewebe.':'بافت فیبروگلاندولار واضح با توزیع هتروژن.','Sehr große Menge fibroglandulären Gewebes.':'مقدار بسیار زیاد بافت فیبروگلاندولار.','FGT ist nicht dasselbe wie mammographische Brustdichte':'FGT با دانسیته ماموگرافیک پستان یکسان نیست','Beide beschreiben zwar die Zusammensetzung der Brust, werden jedoch mit unterschiedlichen Modalitäten beurteilt. Die MRT-Kategorie beschreibt die sichtbare Menge des fibroglandulären Gewebes in der MRT.':'هر دو ترکیب پستان را توصیف می‌کنند، اما با روش‌های متفاوت ارزیابی می‌شوند. دسته MRI مقدار قابل مشاهده بافت فیبروگلاندولار در MRI را نشان می‌دهد.',
  'Normales Parenchym':'پارانشیم طبیعی','BPE beschreibt, wie stark das':'BPE نشان می‌دهد','normale fibroglanduläre Brustgewebe nach Kontrastmittelgabe anreichert':'بافت طبیعی فیبروگلاندولار پس از کنتراست چقدر جذب دارد','BPE-Kategorien in voller Größe öffnen':'باز کردن تصویر کامل دسته‌های BPE','Vier MRT-Beispiele der BPE-Kategorien minimal, mild, moderate und marked':'چهار نمونه MRI از دسته‌های BPE: minimal، mild، moderate و marked','BPE minimal–marked im MRT':'BPE از minimal تا marked در MRI','BI-RADS unterscheidet vier Kategorien:':'BI-RADS چهار دسته را مشخص می‌کند:','Kaum Enhancement des normalen Brustparenchyms.':'تقریباً بدون جذب در پارانشیم طبیعی پستان.','Geringes Enhancement.':'جذب خفیف.','Deutlich sichtbares Enhancement größerer Anteile des Drüsengewebes.':'جذب واضح در بخش‌های بزرگ‌تری از بافت غده‌ای.','Ausgeprägtes Enhancement des normalen Brustparenchyms.':'جذب شدید پارانشیم طبیعی پستان.','Visuelle Beurteilung':'ارزیابی بصری','Diese Einteilung erfolgt visuell. BI-RADS empfiehlt keine starre prozentuale Einteilung.':'این دسته‌بندی بصری است و BI-RADS درصدهای ثابت توصیه نمی‌کند.','FGT und BPE nicht verwechseln':'FGT و BPE را اشتباه نگیرید','FGT beantwortet:':'FGT پاسخ می‌دهد:','Wie viel Drüsengewebe ist vorhanden?':'چه مقدار بافت غده‌ای وجود دارد؟','BPE beantwortet:':'BPE پاسخ می‌دهد:','Wie stark nimmt dieses normale Drüsengewebe Kontrastmittel auf?':'این بافت طبیعی غده‌ای چقدر کنتراست می‌گیرد؟','Daher können beispielsweise beide Konstellationen auftreten:':'بنابراین هر دو ترکیب زیر ممکن است دیده شوند:','viel FGT + minimales BPE':'FGT زیاد + BPE حداقل','oder':'یا','wenig FGT + relativ deutliches BPE':'FGT کم + BPE نسبتاً واضح','Die beiden Parameter sind miteinander verbunden, aber nicht identisch.':'این دو پارامتر مرتبط‌اند اما یکسان نیستند.','Interpretation':'تفسیر','Warum ist BPE wichtig?':'چرا BPE مهم است؟','Starkes BPE kann kleine Läsionen schwieriger erkennbar machen und die Interpretation erschweren.':'BPE شدید می‌تواند تشخیص ضایعات کوچک را دشوار و تفسیر را پیچیده کند.','BPE kann asymmetrisch oder fokal ausgeprägt sein und dadurch eine Läsion imitieren. Sein Ausmaß wird unter anderem durch hormonelle Faktoren beeinflusst.':'BPE می‌تواند نامتقارن یا فوکال باشد و ضایعه را تقلید کند. شدت آن از عوامل هورمونی نیز تأثیر می‌گیرد.','Ein scheinbares Enhancement deshalb immer im Kontext des gesamten Parenchyms beurteilen.':'بنابراین هر جذب ظاهری را در زمینه کل پارانشیم ارزیابی کنید.',
  'Zu klein für eine zuverlässige morphologische Charakterisierung.':'برای توصیف قابل اعتماد مورفولوژیک بیش از حد کوچک است.','Eine echte dreidimensionale Läsion.':'یک ضایعه واقعی سه‌بعدی.','Form, Rand und internes Enhancement können beurteilt werden.':'شکل، حاشیه و جذب داخلی قابل ارزیابی‌اند.','Ein':'یک','ist ein kontrastmittelaufnehmender Bereich, der:':'ناحیه جذب‌کننده کنتراست است که:','vom normalen BPE abgrenzbar ist,':'از BPE طبیعی قابل تفکیک است،','aber keine dreidimensionale Mass bildet':'اما توده سه‌بعدی ایجاد نمی‌کند','und nicht lediglich einen kleinen Focus darstellt.':'و صرفاً یک Focus کوچک نیست.','Nicht sofort fragen':'فوراً نپرسید','„Ist das Krebs?“':'«آیا سرطان است؟»','Schritt 1':'گام ۱','BPE oder echter Befund?':'BPE یا یافته واقعی؟','Schritt 2':'گام ۲','Focus, Mass oder NME?':'Focus، Mass یا NME؟','Schritt 3':'گام ۳','Morphologie · T2 · DWI · Kinetik · Begleitbefunde':'مورفولوژی · T2 · DWI · کینتیک · یافته‌های همراه',
}

export const translate = (lang, value) => (lang === 'en' ? EN[value] : lang === 'fa' ? FA[value] : null) || value
