const L = (de, en, fa) => ({ de, en, fa })

export const pick = (value, lang) => typeof value === 'string' ? value : value?.[lang] || value?.de || ''

export const COPY = {
  mamma: L('Mamma', 'Breast', 'پستان'),
  imaging: L('Bildgebung', 'Imaging', 'تصویربرداری'),
  breastMri: L('Mamma-MRT', 'Breast MRI', 'MRI پستان'),
  title: L('Läsionscharakterisierung', 'Lesion characterisation', 'ارزیابی و توصیف ضایعه'),
  subtitle: L('Morphologie, Enhancement, T2-Signal, Diffusion und Kinetik systematisch kombinieren.', 'Systematically combine morphology, enhancement, T2 signal, diffusion and kinetics.', 'ترکیب سیستماتیک مورفولوژی، Enhancement، سیگنال T2، دیفیوژن و کینتیک.'),
  contents: L('Inhaltsverzeichnis', 'Contents', 'فهرست مطالب'),
  flashcards: L('Flashcards', 'Flashcards', 'فلش‌کارت‌ها'),
  zoom: L('Bild in voller Größe öffnen', 'Open full-size image', 'نمایش تصویر در اندازه کامل'),
  figureCaption: L('Systematische Läsionscharakterisierung in der Mamma-MRT', 'Systematic lesion characterisation in breast MRI', 'ارزیابی سیستماتیک ضایعات در MRI پستان'),
}

export const SECTIONS = [
  { id: 'start', icon: '✦', label: L('Enhancement-Typen', 'Enhancement types', 'انواع Enhancement') },
  { id: 'mass', icon: '●', label: L('Mass', 'Mass', 'Mass') },
  { id: 'nme', icon: '◌', label: L('Non-Mass Enhancement', 'Non-mass enhancement', 'Non-Mass Enhancement') },
  { id: 'kinetik', icon: '↗', label: L('Kinetik', 'Kinetics', 'کینتیک') },
  { id: 't2-diffusion', icon: '≈', label: L('T2 & Diffusion', 'T2 & diffusion', 'T2 و دیفیوژن') },
  { id: 'algorithmus', icon: '✓', label: L('Gesamtbewertung', 'Overall assessment', 'ارزیابی نهایی') },
]

export const MASS_SHAPES = [
  { term: L('Rund', 'Round', 'گرد'), text: L('In zwei Ebenen annähernd kreisförmig.', 'Approximately circular in two planes.', 'در دو صفحه تقریباً دایره‌ای است.'), sub: L('„Rund“ beschreibt nur die Grundform – der Rand kann trotzdem scharf, indistinkt oder spikuliert sein.', '“Round” describes only the basic shape; the margin may still be circumscribed, indistinct or spiculated.', '«گرد» فقط شکل پایه را توصیف می‌کند؛ حاشیه همچنان می‌تواند واضح، نامشخص یا اسپیکوله باشد.'), subStrong: true },
  { term: L('Oval', 'Oval', 'بیضی'), text: L('Elliptisch oder eiförmig mit glatter, länglicher Grundform und ohne deutliche Konturwellen.', 'Elliptical or egg-shaped with a smooth elongated outline and no definite contour undulations.', 'بیضوی یا تخم‌مرغی با نمای کلی صاف و کشیده و بدون موج‌دارشدن واضح کانتور.'), sub: L('Oval + vollständig scharf begrenzt ist eher beruhigend, bleibt aber nur ein Teil der Gesamtbewertung.', 'Oval plus completely circumscribed is more reassuring, but remains only one part of the overall assessment.', 'بیضی همراه با حاشیه کاملاً واضح آرامش‌بخش‌تر است، اما فقط بخشی از ارزیابی نهایی محسوب می‌شود.') },
  { term: L('Lobuliert', 'Lobulated', 'لوبوله'), text: L('Glatte Mass mit sanften, nach außen gewölbten Konturwellen.', 'A smooth mass with gentle outward contour undulations.', 'Mass صاف با موج‌های ملایم و رو به بیرون کانتور است.'), sub: L('Die Lobulierungen gehören zur Form, nicht zur Randqualität.', 'Lobulations describe shape, not margin quality.', 'لوبولاسیون شکل را توصیف می‌کند، نه کیفیت حاشیه را.') },
  { term: L('Irregulär', 'Irregular', 'نامنظم'), text: L('Keine runde oder ovale Grundform: asymmetrische Ausziehungen, Ecken oder ungleichmäßige Kontur.', 'Neither round nor oval: asymmetric projections, corners or an uneven outline.', 'نه گرد و نه بیضی؛ دارای زوائد نامتقارن، گوشه‌ها یا کانتور نامنظم است.'), sub: L('Irreguläre Form erhöht den Verdacht, beweist für sich allein aber keine Malignität.', 'Irregular shape raises suspicion but does not prove malignancy by itself.', 'شکل نامنظم احتمال بدخیمی را افزایش می‌دهد، اما به‌تنهایی تشخیصی نیست.') },
]

export const MASS_MARGINS = [
  { term: L('Scharf begrenzt', 'Circumscribed', 'واضح و صاف'), text: L('Der Rand ist über den gesamten Umfang abrupt und eindeutig vom Nachbargewebe abgrenzbar. Schon ein klar nicht scharf begrenzter Anteil verhindert diese Bezeichnung.', 'The entire margin is abrupt and clearly separated from adjacent tissue. A definite non-circumscribed portion precludes this descriptor.', 'تمام حاشیه به‌طور واضح و ناگهانی از بافت مجاور جداست. وجود یک بخش مشخصِ غیر واضح مانع استفاده از این توصیف می‌شود.'), subItems: [L('Eher benign.', 'More often benign.', 'بیشتر به نفع خوش‌خیمی است.'), L('Besonders zusammen mit ovaler Form und homogenem Enhancement.', 'Especially with oval shape and homogeneous enhancement.', 'به‌ویژه همراه با شکل بیضی و Enhancement همگن.')], level: 'low' },
  { term: L('Indistinkt', 'Indistinct', 'نامشخص'), text: L('Der Rand ist nicht scharf abgrenzbar und geht verschwommen in das Parenchym über, ohne typische strahlenförmige Spiculae.', 'The margin is not sharply defined and blends into the parenchyma without typical radiating spicules.', 'حاشیه واضح نیست و بدون اسپیکول‌های شعاعی تیپیک به‌صورت محو با پارانشیم ادغام می‌شود.'), subItems: [L('Suspekt.', 'Suspicious.', 'مشکوک است.'), L('Auf der räumlich höchstaufgelösten frühen Postkontrast- oder Subtraktionsserie beurteilen.', 'Assess on the highest-resolution early post-contrast or subtraction series.', 'در سری پس از تزریق زودرس یا Subtraction با بالاترین وضوح مکانی ارزیابی شود.')], level: 'mid' },
  { term: L('Spikuliert', 'Spiculated', 'اسپیکوله'), text: L('Feine Linien strahlen vom Läsionsrand in das umgebende Gewebe aus. Das ist mehr als eine bloß unregelmäßige Kontur.', 'Fine lines radiate from the lesion margin into surrounding tissue. This is more than a merely irregular contour.', 'خطوط ظریف از حاشیه ضایعه به بافت اطراف انتشار می‌یابند؛ این یافته فراتر از یک کانتور صرفاً نامنظم است.'), subItems: [L('Hochgradig suspekt.', 'Highly suspicious.', 'به‌شدت مشکوک است.'), L('Postoperative Narbe und radiäre Narbe bei passendem Kontext als Differenzialdiagnosen bedenken.', 'Consider postoperative scar and radial scar as differentials in the appropriate context.', 'اسکار پس از عمل و radial scar در زمینه مناسب از تشخیص‌های افتراقی هستند.')], level: 'high' },
]

export const MASS_ENHANCEMENT = [
  { term: L('Homogen', 'Homogeneous', 'همگن'), text: L('Die gesamte Mass reichert in sich gleichmäßig an.', 'The entire mass enhances uniformly.', 'تمام Mass به‌طور یکنواخت Enhancement دارد.'), sub: L('Achtung: Bei kleinen Läsionen Partialvolumen und Bewegung als scheinbare Inhomogenität ausschließen.', 'Caution: In small lesions, exclude partial volume and motion as causes of apparent heterogeneity.', 'توجه: در ضایعات کوچک، اثر Partial volume و حرکت به‌عنوان علت ناهمگنی ظاهری رد شود.'), subStrong: true },
  { term: L('Heterogen', 'Heterogeneous', 'ناهمگن'), text: L('Innerhalb derselben Mass wechseln stärker und schwächer anreichernde Anteile, etwa durch unterschiedliche Zellulärität, Fibrose oder Nekrose.', 'More and less avidly enhancing areas coexist within the same mass, for example because of variable cellularity, fibrosis or necrosis.', 'در یک Mass نواحی با Enhancement بیشتر و کمتر، مثلاً به‌علت سلولاریته متفاوت، فیبروز یا نکروز، کنار هم دیده می‌شوند.'), sub: L('Vor allem zusammen mit irregulärer Form oder nicht scharfem Rand suspekt.', 'Suspicious particularly with irregular shape or a non-circumscribed margin.', 'به‌ویژه همراه با شکل نامنظم یا حاشیه غیر واضح مشکوک است.') },
  { term: L('Randständige Anreicherung', 'Rim Enhancement', 'Enhancement حاشیه‌ای'), text: L('Ein anreichernder peripherer Saum umgibt ein relativ weniger anreicherndes Zentrum.', 'An enhancing peripheral rim surrounds a relatively less enhancing centre.', 'یک حلقه محیطی دارای Enhancement مرکز با Enhancement کمتر را احاطه می‌کند.'), sub: L('Deutlich suspekt, aber nicht spezifisch: Abszess, Fettnekrose und posttherapeutische Veränderungen können imitieren.', 'Markedly suspicious but not specific: abscess, fat necrosis and post-treatment change may mimic it.', 'به‌وضوح مشکوک اما غیراختصاصی است؛ آبسه، نکروز چربی و تغییرات پس از درمان می‌توانند مشابه باشند.') },
  { term: L('Dunkle interne Septierungen', 'Dark Internal Septations', 'سپتاهای داخلی تیره'), text: L('Glatte lineare Septen innerhalb einer anreichernden Mass bleiben in den Postkontrastserien dunkel.', 'Smooth linear septa within an enhancing mass remain dark on post-contrast images.', 'سپتاهای صاف و خطی درون Mass دارای Enhancement در تصاویر پس از تزریق تیره باقی می‌مانند.'), sub: L('Dunkle interne Septierungen sind ein klassischer Hinweis auf ein Fibroadenom – vorausgesetzt, die Mass ist oval und scharf begrenzt. Bei suspektem Rand oder Wachstum ist eine weitere Abklärung erforderlich.', 'Dark internal septations are a classic clue to a fibroadenoma, provided the mass is oval and circumscribed. A suspicious margin or growth requires further assessment.', 'سپتاهای داخلی تیره یافته‌ای کلاسیک به نفع فیبروآدنوم هستند، به‌شرط آنکه Mass بیضی و با حاشیه واضح باشد. در صورت حاشیه مشکوک یا رشد، بررسی بیشتر ضروری است.'), subStrong: true },
]

export const MASS_WORKFLOW = [
  { title: L('1 · Form festlegen', '1 · Define shape', '۱ · تعیین شکل'), text: L('Zuerst die geometrische Grundform in zwei Ebenen beurteilen: rund, oval, lobuliert oder irregulär. Noch keine Randqualität hineininterpretieren.', 'First assess the basic geometry in two planes: round, oval, lobulated or irregular. Do not mix margin quality into this step.', 'ابتدا هندسه پایه را در دو صفحه به‌صورت گرد، بیضی، لوبوله یا نامنظم ارزیابی کنید و کیفیت حاشیه را وارد این مرحله نکنید.') },
  { title: L('2 · Verdächtigsten Rand benennen', '2 · Name the most suspicious margin', '۲ · نام‌گذاری مشکوک‌ترین حاشیه'), text: L('Den gesamten Umfang durchscrollen. Ist ein relevanter Abschnitt indistinkt oder spikuliert, darf die Mass nicht als vollständig scharf begrenzt gelten.', 'Scroll around the entire circumference. If a relevant portion is indistinct or spiculated, the mass is not completely circumscribed.', 'تمام محیط ضایعه را مرور کنید. اگر بخشی قابل‌توجه نامشخص یا اسپیکوله باشد، Mass کاملاً واضح محسوب نمی‌شود.') },
  { title: L('3 · Inneres Muster ergänzen', '3 · Add internal enhancement', '۳ · افزودن الگوی داخلی'), text: L('Erst danach homogen, heterogen, randständig oder mit dunklen Septen beschreiben. Die Kombination der Merkmale ist wichtiger als ein einzelner Deskriptor.', 'Then describe enhancement as homogeneous, heterogeneous, rim or with dark septations. The combination matters more than a single descriptor.', 'سپس Enhancement را همگن، ناهمگن، حاشیه‌ای یا همراه با سپتای تیره توصیف کنید. ترکیب ویژگی‌ها از یک توصیف منفرد مهم‌تر است.') },
]

export const NME_DISTRIBUTION = [
  { term: L('Fokal', 'Focal', 'کانونی'), text: L('Kompaktes NME in einem kleinen, umschriebenen Areal, das weniger als einen Quadranten einnimmt; normales Gewebe oder Fett kann darin eingestreut bleiben.', 'Compact NME in a small, confined area occupying less than one quadrant; normal tissue or fat may remain interspersed.', 'NME فشرده در ناحیه‌ای کوچک و محدود که کمتر از یک کوادرانت را درگیر می‌کند؛ بافت طبیعی یا چربی ممکن است در آن باقی بماند.'), sub: L('Nicht mit einer kleinen Mass verwechseln: Es fehlt die konvexe, raumfordernde Kontur.', 'Do not confuse it with a small mass: the convex space-occupying contour is absent.', 'با Mass کوچک اشتباه نشود؛ کانتور محدب و فضاگیر وجود ندارد.') },
  { term: L('Linear', 'Linear', 'خطی'), text: L('Anreicherung entlang einer Linie, die gerade oder verzweigt verlaufen kann und häufig einem einzelnen Gang folgt.', 'Enhancement along a line that may be straight or branching and often follows a single duct.', 'Enhancement در امتداد یک خط که می‌تواند مستقیم یا شاخه‌دار باشد و اغلب یک مجرا را دنبال می‌کند.'), sub: L('Neu, einseitig und klumpig-linear ist deutlich verdächtiger als dünn, glatt und beidseits ähnlich.', 'New, unilateral clumped linear enhancement is much more concerning than thin, smooth and bilaterally similar enhancement.', 'الگوی خطی جدید، یک‌طرفه و Clumped بسیار مشکوک‌تر از الگوی نازک، صاف و دوطرفه مشابه است.') },
  { term: L('Segmental', 'Segmental', 'سگمنتال'), text: L('Keil- oder dreieckförmige Anreicherung mit Spitze zur Mamille; sie bildet das verzweigte Territorium eines Gangsystems ab.', 'Wedge- or triangular enhancement with its apex toward the nipple, mapping the branching territory of a ductal system.', 'Enhancement گوه‌ای یا مثلثی با رأس به‌سمت نوک پستان که قلمرو شاخه‌دار یک سیستم مجرایی را نشان می‌دهد.'), sub: L('Wichtiger Warnhinweis auf DCIS oder einen malignen duktalen Prozess – Ausdehnung vollständig messen.', 'An important warning sign for DCIS or a malignant ductal process; measure the full extent.', 'نشانه مهم DCIS یا فرایند بدخیم مجرایی است؛ وسعت کامل باید اندازه‌گیری شود.') },
  { term: L('Regional', 'Regional', 'ناحیه‌ای'), text: L('Größeres zusammenhängendes Volumen, das keinem einzelnen Gangsystem entspricht. Die Ausdehnung ist flächig statt keilförmig.', 'A larger contiguous volume not conforming to a single ductal system. Its extent is geographic rather than wedge-shaped.', 'حجم پیوسته بزرگ‌تر که با یک سیستم مجرایی واحد تطابق ندارد و به‌جای شکل گوه‌ای، گستره‌ای جغرافیایی دارد.'), sub: L('Symmetrie, BPE, Voraufnahmen und internes Muster entscheiden über die Einordnung.', 'Symmetry, BPE, prior studies and internal pattern determine its significance.', 'تقارن، BPE، بررسی‌های قبلی و الگوی داخلی در تفسیر اهمیت دارند.') },
  { term: L('Diffus', 'Diffuse', 'منتشر'), text: L('Weitläufige, eher zufällige Verteilung über große Teile der Brust, ohne Orientierung an einem einzelnen Gangsystem.', 'Widespread, relatively random enhancement throughout much of the breast without alignment to one ductal system.', 'Enhancement گسترده و نسبتاً تصادفی در بخش بزرگی از پستان، بدون جهت‌گیری به یک سیستم مجرایی.'), sub: L('Häufig hormonell oder entzündlich; einseitige neue diffuse Anreicherung mit Haut- oder Ödemzeichen ist jedoch suspekt.', 'Often hormonal or inflammatory; new unilateral diffuse enhancement with skin or oedema findings is concerning.', 'اغلب هورمونی یا التهابی است؛ اما Enhancement منتشر جدید و یک‌طرفه همراه با علائم پوستی یا ادم مشکوک است.') },
]

export const NME_PATTERNS = [
  { term: L('Homogen', 'Homogeneous', 'همگن'), text: L('Das gesamte NME-Areal reichert relativ gleichmäßig an. Vorher prüfen, ob es sich nicht um normales, symmetrisches BPE handelt.', 'The entire NME area enhances relatively uniformly. First ensure this is not normal symmetric BPE.', 'تمام ناحیه NME نسبتاً یکنواخت Enhancement دارد؛ ابتدا باید BPE طبیعی و متقارن رد شود.'), sub: L('Eher weniger suspekt, aber Verteilung, Neuigkeit und Asymmetrie können die Bewertung anheben.', 'Generally less suspicious, but distribution, newness and asymmetry may raise concern.', 'معمولاً کمتر مشکوک است، اما توزیع، جدید بودن و عدم تقارن می‌توانند سطح نگرانی را افزایش دهند.') },
  { term: L('Heterogen', 'Heterogeneous', 'ناهمگن'), text: L('Fleckige Areale unterschiedlicher Intensität liegen innerhalb derselben Verteilung, ohne das dichte „Kopfsteinpflaster“ eines klumpigen Musters.', 'Patchy areas of varying intensity occur within the same distribution without the dense cobblestone appearance of a clumped pattern.', 'نواحی لکه‌ای با شدت‌های متفاوت در یک توزیع دیده می‌شوند، بدون نمای سنگفرشی متراکم الگوی Clumped.'), sub: L('Unspezifisch; in linearer oder segmentaler Verteilung verdächtiger.', 'Nonspecific; more concerning in a linear or segmental distribution.', 'غیراختصاصی است؛ در توزیع خطی یا سگمنتال مشکوک‌تر می‌شود.') },
  { term: L('Klumpig', 'Clumped', 'توده‌ای و خوشه‌ای'), text: L('Unregelmäßige, pflastersteinartige Anreicherungsinseln liegen dicht beieinander und können teilweise konfluieren.', 'Irregular cobblestone-like enhancing foci are tightly packed and may partially coalesce.', 'کانون‌های نامنظم و شبیه سنگفرش به‌طور متراکم کنار هم قرار گرفته و ممکن است تا حدی به هم بپیوندند.'), sub: L('Suspekt – besonders bei neuer linearer oder segmentaler Verteilung.', 'Suspicious, especially when new and linear or segmental.', 'مشکوک است، به‌ویژه اگر جدید و با توزیع خطی یا سگمنتال باشد.') },
  { term: L('Gruppiert ringförmig', 'Clustered Ring', 'حلقه‌های خوشه‌ای'), text: L('Viele feine Ringe um kleine Gänge oder duktuläre Strukturen ergeben ein gruppiertes „Mikroring“-Muster.', 'Numerous fine rings around small ducts or ductules create a grouped “microring” pattern.', 'حلقه‌های ظریف متعدد پیرامون مجاری کوچک، الگوی گروهی «میکرو‌رینگ» ایجاد می‌کنند.'), sub: L('Besonders suspekt und häufig mit DCIS oder invasiver Malignität assoziiert.', 'Particularly suspicious and often associated with DCIS or invasive malignancy.', 'به‌ویژه مشکوک و اغلب با DCIS یا بدخیمی مهاجم مرتبط است.') },
]

export const NME_WORKFLOW = [
  { title: L('1 · Echtes NME bestätigen', '1 · Confirm true NME', '۱ · تأیید NME واقعی'), text: L('Subtraktion auf Fehlregistrierung prüfen, Gefäße verfolgen und mit Gegenseite sowie normalem BPE vergleichen. Nicht jedes Enhancement ist eine Läsion.', 'Check subtraction for misregistration, follow vessels, and compare with the opposite breast and normal BPE. Not every enhancement is a lesion.', 'Subtraction را از نظر Misregistration بررسی کنید، عروق را دنبال کرده و با پستان مقابل و BPE طبیعی مقایسه کنید. هر Enhancement الزاماً ضایعه نیست.') },
  { title: L('2 · Verteilung kartieren', '2 · Map distribution', '۲ · ترسیم توزیع'), text: L('Folgt das Enhancement einem Gang? Ist es keilförmig, flächig oder diffus? Verteilung beschreibt Weg und Ausdehnung – nicht die innere Textur.', 'Does enhancement follow a duct? Is it wedge-shaped, geographic or diffuse? Distribution describes route and extent, not internal texture.', 'آیا Enhancement یک مجرا را دنبال می‌کند و گوه‌ای، جغرافیایی یا منتشر است؟ توزیع مسیر و وسعت را توصیف می‌کند، نه بافت داخلی را.') },
  { title: L('3 · Internes Muster bestimmen', '3 · Define internal pattern', '۳ · تعیین الگوی داخلی'), text: L('Danach homogen, heterogen, klumpig oder gruppiert-ringförmig wählen. Erst die Kombination aus Verteilung und Muster ergibt die morphologische Aussage.', 'Then select homogeneous, heterogeneous, clumped or clustered ring. The morphological message comes from combining distribution and pattern.', 'سپس الگو را همگن، ناهمگن، Clumped یا Clustered ring تعیین کنید. پیام مورفولوژیک از ترکیب توزیع و الگو به‌دست می‌آید.') },
]

export const KINETIC_PHASES = [
  { title: L('Initiale Phase', 'Initial phase', 'فاز اولیه'), text: L('Wie schnell steigt das Enhancement nach Kontrastmittelgabe an?', 'How quickly does enhancement rise after contrast administration?', 'Enhancement پس از تزریق ماده حاجب با چه سرعتی افزایش می‌یابد؟'), items: ['slow', 'medium', 'rapid'] },
  { title: L('Späte Phase', 'Delayed phase', 'فاز تأخیری'), text: L('Wie verhält sich das Signal nach dem initialen Anstieg?', 'How does the signal behave after the initial rise?', 'سیگنال پس از افزایش اولیه چه تغییری می‌کند؟'), items: ['persistent', 'plateau', 'washout'] },
]

export const CURVES = [
  { type: 'I', name: 'Persistent', symbol: '↗', tag: L('eher benign', 'more likely benign', 'بیشتر خوش‌خیم'), text: L('Das Enhancement nimmt weiter zu – eher benign.', 'Enhancement continues to increase – more often benign.', 'Enhancement همچنان افزایش می‌یابد؛ بیشتر به نفع خوش‌خیمی است.'), tone: 'green' },
  { type: 'II', name: 'Plateau', symbol: '↗ →', text: L('Nach dem Anstieg bleibt das Signal ungefähr konstant – intermediär/suspekt.', 'After the rise, the signal remains approximately constant – intermediate/suspicious.', 'پس از افزایش اولیه، سیگنال تقریباً ثابت می‌ماند؛ بینابینی/مشکوک.'), tone: 'amber' },
  { type: 'III', name: 'Washout', symbol: '↗ ↘', tag: L('malignomsuspekt', 'suspicious for malignancy', 'مشکوک به بدخیمی'), text: L('Nach starker Aufnahme nimmt das Signal wieder ab – stärker malignitätsverdächtig.', 'After strong uptake, the signal decreases – more suspicious for malignancy.', 'پس از Enhancement شدید، سیگنال کاهش می‌یابد؛ بیشتر به نفع بدخیمی است.'), tone: 'red' },
]

export const SUMMARY_STEPS = [
  L('Mass oder NME?', 'Mass or NME?', 'Mass یا NME؟'),
  L('Mass: Form → Rand → internes Anreicherungsmuster', 'Mass: shape → margin → internal enhancement', 'Mass: شکل ← حاشیه ← الگوی Enhancement داخلی'),
  L('NME: Verteilung → internes Anreicherungsmuster', 'NME: distribution → internal enhancement pattern', 'NME: توزیع ← الگوی Enhancement داخلی'),
  L('Danach: T2 → DWI/ADC → Kinetik → Voraufnahmen', 'Then: T2 → DWI/ADC → kinetics → prior studies', 'سپس: T2 ← DWI/ADC ← کینتیک ← بررسی‌های قبلی'),
]
